// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class DeviceTokenReportRequest;
@class DeviceTokenReportRequest_Builder;

@interface DeviceTokenReportProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface DeviceTokenReportRequest : PBGeneratedMessage {
@private
  BOOL hasDeviceToken_:1;
  BOOL hasMdn_:1;
  BOOL hasMobileType_:1;
  NSString* deviceToken;
  NSString* mdn;
  NSString* mobileType;
}
- (BOOL) hasDeviceToken;
- (BOOL) hasMdn;
- (BOOL) hasMobileType;
@property (readonly, retain) NSString* deviceToken;
@property (readonly, retain) NSString* mdn;
@property (readonly, retain) NSString* mobileType;

+ (DeviceTokenReportRequest*) defaultInstance;
- (DeviceTokenReportRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DeviceTokenReportRequest_Builder*) builder;
+ (DeviceTokenReportRequest_Builder*) builder;
+ (DeviceTokenReportRequest_Builder*) builderWithPrototype:(DeviceTokenReportRequest*) prototype;

+ (DeviceTokenReportRequest*) parseFromData:(NSData*) data;
+ (DeviceTokenReportRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeviceTokenReportRequest*) parseFromInputStream:(NSInputStream*) input;
+ (DeviceTokenReportRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DeviceTokenReportRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DeviceTokenReportRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DeviceTokenReportRequest_Builder : PBGeneratedMessage_Builder {
@private
  DeviceTokenReportRequest* result;
}

- (DeviceTokenReportRequest*) defaultInstance;

- (DeviceTokenReportRequest_Builder*) clear;
- (DeviceTokenReportRequest_Builder*) clone;

- (DeviceTokenReportRequest*) build;
- (DeviceTokenReportRequest*) buildPartial;

- (DeviceTokenReportRequest_Builder*) mergeFrom:(DeviceTokenReportRequest*) other;
- (DeviceTokenReportRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DeviceTokenReportRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeviceToken;
- (NSString*) deviceToken;
- (DeviceTokenReportRequest_Builder*) setDeviceToken:(NSString*) value;
- (DeviceTokenReportRequest_Builder*) clearDeviceToken;

- (BOOL) hasMdn;
- (NSString*) mdn;
- (DeviceTokenReportRequest_Builder*) setMdn:(NSString*) value;
- (DeviceTokenReportRequest_Builder*) clearMdn;

- (BOOL) hasMobileType;
- (NSString*) mobileType;
- (DeviceTokenReportRequest_Builder*) setMobileType:(NSString*) value;
- (DeviceTokenReportRequest_Builder*) clearMobileType;
@end

