// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "ContactProto.pb.h"

@class Address;
@class Address_Builder;
@class CallLog;
@class CallLog_Builder;
@class Category;
@class Category_Builder;
@class Contact;
@class ContactMyCardRequest;
@class ContactMyCardRequest_Builder;
@class ContactMyCardResponse;
@class ContactMyCardResponse_Builder;
@class Contact_Builder;
@class Email;
@class Email_Builder;
@class Employed;
@class Employed_Builder;
@class FileInfo;
@class FileInfo_Builder;
@class Group;
@class Group_Builder;
@class InstantMessage;
@class InstantMessage_Builder;
@class Name;
@class Name_Builder;
@class Phone;
@class Phone_Builder;
@class PortraitData;
@class PortraitData_Builder;
@class Sms;
@class SmsSummary;
@class SmsSummary_Builder;
@class Sms_Builder;
@class UabError;
@class UabError_Builder;
@class Website;
@class Website_Builder;

@interface ContactMycardProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ContactMyCardRequest : PBGeneratedMessage {
@private
  BOOL hasIsMoreCard_:1;
  BOOL isMoreCard_:1;
  NSMutableArray* mutableUserIdList;
}
- (BOOL) hasIsMoreCard;
- (BOOL) isMoreCard;
- (NSArray*) userIdList;
- (int32_t) userIdAtIndex:(int32_t) index;

+ (ContactMyCardRequest*) defaultInstance;
- (ContactMyCardRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactMyCardRequest_Builder*) builder;
+ (ContactMyCardRequest_Builder*) builder;
+ (ContactMyCardRequest_Builder*) builderWithPrototype:(ContactMyCardRequest*) prototype;

+ (ContactMyCardRequest*) parseFromData:(NSData*) data;
+ (ContactMyCardRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactMyCardRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ContactMyCardRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactMyCardRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactMyCardRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactMyCardRequest_Builder : PBGeneratedMessage_Builder {
@private
  ContactMyCardRequest* result;
}

- (ContactMyCardRequest*) defaultInstance;

- (ContactMyCardRequest_Builder*) clear;
- (ContactMyCardRequest_Builder*) clone;

- (ContactMyCardRequest*) build;
- (ContactMyCardRequest*) buildPartial;

- (ContactMyCardRequest_Builder*) mergeFrom:(ContactMyCardRequest*) other;
- (ContactMyCardRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactMyCardRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) userIdList;
- (int32_t) userIdAtIndex:(int32_t) index;
- (ContactMyCardRequest_Builder*) replaceUserIdAtIndex:(int32_t) index with:(int32_t) value;
- (ContactMyCardRequest_Builder*) addUserId:(int32_t) value;
- (ContactMyCardRequest_Builder*) addAllUserId:(NSArray*) values;
- (ContactMyCardRequest_Builder*) clearUserIdList;

- (BOOL) hasIsMoreCard;
- (BOOL) isMoreCard;
- (ContactMyCardRequest_Builder*) setIsMoreCard:(BOOL) value;
- (ContactMyCardRequest_Builder*) clearIsMoreCard;
@end

@interface ContactMyCardResponse : PBGeneratedMessage {
@private
  BOOL hasBusinessCard_:1;
  Contact* businessCard;
  NSMutableArray* mutableBusinessCardsList;
}
- (BOOL) hasBusinessCard;
@property (readonly, retain) Contact* businessCard;
- (NSArray*) businessCardsList;
- (Contact*) businessCardsAtIndex:(int32_t) index;

+ (ContactMyCardResponse*) defaultInstance;
- (ContactMyCardResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactMyCardResponse_Builder*) builder;
+ (ContactMyCardResponse_Builder*) builder;
+ (ContactMyCardResponse_Builder*) builderWithPrototype:(ContactMyCardResponse*) prototype;

+ (ContactMyCardResponse*) parseFromData:(NSData*) data;
+ (ContactMyCardResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactMyCardResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ContactMyCardResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactMyCardResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactMyCardResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactMyCardResponse_Builder : PBGeneratedMessage_Builder {
@private
  ContactMyCardResponse* result;
}

- (ContactMyCardResponse*) defaultInstance;

- (ContactMyCardResponse_Builder*) clear;
- (ContactMyCardResponse_Builder*) clone;

- (ContactMyCardResponse*) build;
- (ContactMyCardResponse*) buildPartial;

- (ContactMyCardResponse_Builder*) mergeFrom:(ContactMyCardResponse*) other;
- (ContactMyCardResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactMyCardResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasBusinessCard;
- (Contact*) businessCard;
- (ContactMyCardResponse_Builder*) setBusinessCard:(Contact*) value;
- (ContactMyCardResponse_Builder*) setBusinessCardBuilder:(Contact_Builder*) builderForValue;
- (ContactMyCardResponse_Builder*) mergeBusinessCard:(Contact*) value;
- (ContactMyCardResponse_Builder*) clearBusinessCard;

- (NSArray*) businessCardsList;
- (Contact*) businessCardsAtIndex:(int32_t) index;
- (ContactMyCardResponse_Builder*) replaceBusinessCardsAtIndex:(int32_t) index with:(Contact*) value;
- (ContactMyCardResponse_Builder*) addBusinessCards:(Contact*) value;
- (ContactMyCardResponse_Builder*) addAllBusinessCards:(NSArray*) values;
- (ContactMyCardResponse_Builder*) clearBusinessCardsList;
@end

