// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "ContactProto.pb.h"

@class Address;
@class Address_Builder;
@class CallLog;
@class CallLog_Builder;
@class Category;
@class Category_Builder;
@class Contact;
@class ContactShareRequest;
@class ContactShareRequest_Builder;
@class ContactShareResponse;
@class ContactShareResponse_Builder;
@class Contact_Builder;
@class Email;
@class Email_Builder;
@class Employed;
@class Employed_Builder;
@class FileInfo;
@class FileInfo_Builder;
@class Group;
@class Group_Builder;
@class InstantMessage;
@class InstantMessage_Builder;
@class Name;
@class Name_Builder;
@class Phone;
@class Phone_Builder;
@class PortraitData;
@class PortraitData_Builder;
@class Sms;
@class SmsSummary;
@class SmsSummary_Builder;
@class Sms_Builder;
@class UabError;
@class UabError_Builder;
@class Website;
@class Website_Builder;

@interface ContactShareProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ContactShareRequest : PBGeneratedMessage {
@private
  BOOL hasUsername_:1;
  NSString* username;
  NSMutableArray* mutableContactList;
}
- (BOOL) hasUsername;
@property (readonly, retain) NSString* username;
- (NSArray*) contactList;
- (Contact*) contactAtIndex:(int32_t) index;

+ (ContactShareRequest*) defaultInstance;
- (ContactShareRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactShareRequest_Builder*) builder;
+ (ContactShareRequest_Builder*) builder;
+ (ContactShareRequest_Builder*) builderWithPrototype:(ContactShareRequest*) prototype;

+ (ContactShareRequest*) parseFromData:(NSData*) data;
+ (ContactShareRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactShareRequest*) parseFromInputStream:(NSInputStream*) input;
+ (ContactShareRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactShareRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactShareRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactShareRequest_Builder : PBGeneratedMessage_Builder {
@private
  ContactShareRequest* result;
}

- (ContactShareRequest*) defaultInstance;

- (ContactShareRequest_Builder*) clear;
- (ContactShareRequest_Builder*) clone;

- (ContactShareRequest*) build;
- (ContactShareRequest*) buildPartial;

- (ContactShareRequest_Builder*) mergeFrom:(ContactShareRequest*) other;
- (ContactShareRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactShareRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) contactList;
- (Contact*) contactAtIndex:(int32_t) index;
- (ContactShareRequest_Builder*) replaceContactAtIndex:(int32_t) index with:(Contact*) value;
- (ContactShareRequest_Builder*) addContact:(Contact*) value;
- (ContactShareRequest_Builder*) addAllContact:(NSArray*) values;
- (ContactShareRequest_Builder*) clearContactList;

- (BOOL) hasUsername;
- (NSString*) username;
- (ContactShareRequest_Builder*) setUsername:(NSString*) value;
- (ContactShareRequest_Builder*) clearUsername;
@end

@interface ContactShareResponse : PBGeneratedMessage {
@private
  BOOL hasResCode_:1;
  BOOL hasResMsg_:1;
  BOOL hasShareUrl_:1;
  BOOL hasExtractCode_:1;
  int32_t resCode;
  NSString* resMsg;
  NSString* shareUrl;
  NSString* extractCode;
}
- (BOOL) hasResCode;
- (BOOL) hasResMsg;
- (BOOL) hasShareUrl;
- (BOOL) hasExtractCode;
@property (readonly) int32_t resCode;
@property (readonly, retain) NSString* resMsg;
@property (readonly, retain) NSString* shareUrl;
@property (readonly, retain) NSString* extractCode;

+ (ContactShareResponse*) defaultInstance;
- (ContactShareResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ContactShareResponse_Builder*) builder;
+ (ContactShareResponse_Builder*) builder;
+ (ContactShareResponse_Builder*) builderWithPrototype:(ContactShareResponse*) prototype;

+ (ContactShareResponse*) parseFromData:(NSData*) data;
+ (ContactShareResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactShareResponse*) parseFromInputStream:(NSInputStream*) input;
+ (ContactShareResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ContactShareResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ContactShareResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ContactShareResponse_Builder : PBGeneratedMessage_Builder {
@private
  ContactShareResponse* result;
}

- (ContactShareResponse*) defaultInstance;

- (ContactShareResponse_Builder*) clear;
- (ContactShareResponse_Builder*) clone;

- (ContactShareResponse*) build;
- (ContactShareResponse*) buildPartial;

- (ContactShareResponse_Builder*) mergeFrom:(ContactShareResponse*) other;
- (ContactShareResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ContactShareResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasResCode;
- (int32_t) resCode;
- (ContactShareResponse_Builder*) setResCode:(int32_t) value;
- (ContactShareResponse_Builder*) clearResCode;

- (BOOL) hasResMsg;
- (NSString*) resMsg;
- (ContactShareResponse_Builder*) setResMsg:(NSString*) value;
- (ContactShareResponse_Builder*) clearResMsg;

- (BOOL) hasShareUrl;
- (NSString*) shareUrl;
- (ContactShareResponse_Builder*) setShareUrl:(NSString*) value;
- (ContactShareResponse_Builder*) clearShareUrl;

- (BOOL) hasExtractCode;
- (NSString*) extractCode;
- (ContactShareResponse_Builder*) setExtractCode:(NSString*) value;
- (ContactShareResponse_Builder*) clearExtractCode;
@end

