// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class CTPassRequest;
@class CTPassRequest_Builder;

@interface CtpassRequestProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface CTPassRequest : PBGeneratedMessage {
@private
  BOOL hasMdn_:1;
  BOOL hasSeqId_:1;
  BOOL hasRandom_:1;
  NSString* mdn;
  NSString* seqId;
  NSString* random;
}
- (BOOL) hasMdn;
- (BOOL) hasSeqId;
- (BOOL) hasRandom;
@property (readonly, retain) NSString* mdn;
@property (readonly, retain) NSString* seqId;
@property (readonly, retain) NSString* random;

+ (CTPassRequest*) defaultInstance;
- (CTPassRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CTPassRequest_Builder*) builder;
+ (CTPassRequest_Builder*) builder;
+ (CTPassRequest_Builder*) builderWithPrototype:(CTPassRequest*) prototype;

+ (CTPassRequest*) parseFromData:(NSData*) data;
+ (CTPassRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CTPassRequest*) parseFromInputStream:(NSInputStream*) input;
+ (CTPassRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CTPassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CTPassRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CTPassRequest_Builder : PBGeneratedMessage_Builder {
@private
  CTPassRequest* result;
}

- (CTPassRequest*) defaultInstance;

- (CTPassRequest_Builder*) clear;
- (CTPassRequest_Builder*) clone;

- (CTPassRequest*) build;
- (CTPassRequest*) buildPartial;

- (CTPassRequest_Builder*) mergeFrom:(CTPassRequest*) other;
- (CTPassRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CTPassRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMdn;
- (NSString*) mdn;
- (CTPassRequest_Builder*) setMdn:(NSString*) value;
- (CTPassRequest_Builder*) clearMdn;

- (BOOL) hasSeqId;
- (NSString*) seqId;
- (CTPassRequest_Builder*) setSeqId:(NSString*) value;
- (CTPassRequest_Builder*) clearSeqId;

- (BOOL) hasRandom;
- (NSString*) random;
- (CTPassRequest_Builder*) setRandom:(NSString*) value;
- (CTPassRequest_Builder*) clearRandom;
@end

