// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "BaseTypeProto.pb.h"

@class Address;
@class Address_Builder;
@class Category;
@class Category_Builder;
@class Email;
@class Email_Builder;
@class Employed;
@class Employed_Builder;
@class EncryptedData;
@class EncryptedData_Builder;
@class InstantMessage;
@class InstantMessage_Builder;
@class Name;
@class Name_Builder;
@class Phone;
@class Phone_Builder;
@class PortraitData;
@class PortraitData_Builder;
@class Sms;
@class SmsSummary;
@class SmsSummary_Builder;
@class Sms_Builder;
@class UabError;
@class UabError_Builder;
@class Website;
@class Website_Builder;

@interface EncryptedProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface EncryptedData : PBGeneratedMessage {
@private
  BOOL hasName_:1;
  Name* name;
}
- (BOOL) hasName;
@property (readonly, retain) Name* name;

+ (EncryptedData*) defaultInstance;
- (EncryptedData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (EncryptedData_Builder*) builder;
+ (EncryptedData_Builder*) builder;
+ (EncryptedData_Builder*) builderWithPrototype:(EncryptedData*) prototype;

+ (EncryptedData*) parseFromData:(NSData*) data;
+ (EncryptedData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EncryptedData*) parseFromInputStream:(NSInputStream*) input;
+ (EncryptedData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (EncryptedData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (EncryptedData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface EncryptedData_Builder : PBGeneratedMessage_Builder {
@private
  EncryptedData* result;
}

- (EncryptedData*) defaultInstance;

- (EncryptedData_Builder*) clear;
- (EncryptedData_Builder*) clone;

- (EncryptedData*) build;
- (EncryptedData*) buildPartial;

- (EncryptedData_Builder*) mergeFrom:(EncryptedData*) other;
- (EncryptedData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (EncryptedData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (Name*) name;
- (EncryptedData_Builder*) setName:(Name*) value;
- (EncryptedData_Builder*) setNameBuilder:(Name_Builder*) builderForValue;
- (EncryptedData_Builder*) mergeName:(Name*) value;
- (EncryptedData_Builder*) clearName;
@end

