// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "GetSysMsgProto.pb.h"

@implementation GetSysMsgProtoRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [GetSysMsgProtoRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [BaseTypeProtoRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface SysMsg ()
@property int32_t jobServerId;
@property int64_t timestamp;
@property (retain) NSString* startDate;
@property (retain) NSString* endDate;
@property int32_t displayType;
@property (retain) NSString* title;
@property (retain) NSString* content;
@property int32_t frequency;
@property int32_t msgType;
@property int32_t netType;
@property (retain) NSString* urlDetail;
@property (retain) NSString* imgLogo;
@property (retain) NSString* imgTitleUrl;
@property (retain) NSString* imgContentUrl1;
@property (retain) NSString* imgContentUrl2;
@property (retain) NSString* imgContentUrl3;
@property (retain) NSString* readAmount;
@property int32_t random;
@property int32_t memberType;
@property int32_t isTop;
@end

@implementation SysMsg

- (BOOL) hasJobServerId {
  return !!hasJobServerId_;
}
- (void) setHasJobServerId:(BOOL) value {
  hasJobServerId_ = !!value;
}
@synthesize jobServerId;
- (BOOL) hasTimestamp {
  return !!hasTimestamp_;
}
- (void) setHasTimestamp:(BOOL) value {
  hasTimestamp_ = !!value;
}
@synthesize timestamp;
- (BOOL) hasStartDate {
  return !!hasStartDate_;
}
- (void) setHasStartDate:(BOOL) value {
  hasStartDate_ = !!value;
}
@synthesize startDate;
- (BOOL) hasEndDate {
  return !!hasEndDate_;
}
- (void) setHasEndDate:(BOOL) value {
  hasEndDate_ = !!value;
}
@synthesize endDate;
- (BOOL) hasDisplayType {
  return !!hasDisplayType_;
}
- (void) setHasDisplayType:(BOOL) value {
  hasDisplayType_ = !!value;
}
@synthesize displayType;
- (BOOL) hasTitle {
  return !!hasTitle_;
}
- (void) setHasTitle:(BOOL) value {
  hasTitle_ = !!value;
}
@synthesize title;
- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) value {
  hasContent_ = !!value;
}
@synthesize content;
- (BOOL) hasFrequency {
  return !!hasFrequency_;
}
- (void) setHasFrequency:(BOOL) value {
  hasFrequency_ = !!value;
}
@synthesize frequency;
- (BOOL) hasMsgType {
  return !!hasMsgType_;
}
- (void) setHasMsgType:(BOOL) value {
  hasMsgType_ = !!value;
}
@synthesize msgType;
- (BOOL) hasNetType {
  return !!hasNetType_;
}
- (void) setHasNetType:(BOOL) value {
  hasNetType_ = !!value;
}
@synthesize netType;
- (BOOL) hasUrlDetail {
  return !!hasUrlDetail_;
}
- (void) setHasUrlDetail:(BOOL) value {
  hasUrlDetail_ = !!value;
}
@synthesize urlDetail;
- (BOOL) hasImgLogo {
  return !!hasImgLogo_;
}
- (void) setHasImgLogo:(BOOL) value {
  hasImgLogo_ = !!value;
}
@synthesize imgLogo;
- (BOOL) hasImgTitleUrl {
  return !!hasImgTitleUrl_;
}
- (void) setHasImgTitleUrl:(BOOL) value {
  hasImgTitleUrl_ = !!value;
}
@synthesize imgTitleUrl;
- (BOOL) hasImgContentUrl1 {
  return !!hasImgContentUrl1_;
}
- (void) setHasImgContentUrl1:(BOOL) value {
  hasImgContentUrl1_ = !!value;
}
@synthesize imgContentUrl1;
- (BOOL) hasImgContentUrl2 {
  return !!hasImgContentUrl2_;
}
- (void) setHasImgContentUrl2:(BOOL) value {
  hasImgContentUrl2_ = !!value;
}
@synthesize imgContentUrl2;
- (BOOL) hasImgContentUrl3 {
  return !!hasImgContentUrl3_;
}
- (void) setHasImgContentUrl3:(BOOL) value {
  hasImgContentUrl3_ = !!value;
}
@synthesize imgContentUrl3;
- (BOOL) hasReadAmount {
  return !!hasReadAmount_;
}
- (void) setHasReadAmount:(BOOL) value {
  hasReadAmount_ = !!value;
}
@synthesize readAmount;
- (BOOL) hasRandom {
  return !!hasRandom_;
}
- (void) setHasRandom:(BOOL) value {
  hasRandom_ = !!value;
}
@synthesize random;
- (BOOL) hasMemberType {
  return !!hasMemberType_;
}
- (void) setHasMemberType:(BOOL) value {
  hasMemberType_ = !!value;
}
@synthesize memberType;
- (BOOL) hasIsTop {
  return !!hasIsTop_;
}
- (void) setHasIsTop:(BOOL) value {
  hasIsTop_ = !!value;
}
@synthesize isTop;
- (void) dealloc {
  self.startDate = nil;
  self.endDate = nil;
  self.title = nil;
  self.content = nil;
  self.urlDetail = nil;
  self.imgLogo = nil;
  self.imgTitleUrl = nil;
  self.imgContentUrl1 = nil;
  self.imgContentUrl2 = nil;
  self.imgContentUrl3 = nil;
  self.readAmount = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.jobServerId = 0;
    self.timestamp = 0L;
    self.startDate = @"";
    self.endDate = @"";
    self.displayType = 0;
    self.title = @"";
    self.content = @"";
    self.frequency = 0;
    self.msgType = 0;
    self.netType = 0;
    self.urlDetail = @"";
    self.imgLogo = @"";
    self.imgTitleUrl = @"";
    self.imgContentUrl1 = @"";
    self.imgContentUrl2 = @"";
    self.imgContentUrl3 = @"";
    self.readAmount = @"";
    self.random = 0;
    self.memberType = 0;
    self.isTop = 0;
  }
  return self;
}
static SysMsg* defaultSysMsgInstance = nil;
+ (void) initialize {
  if (self == [SysMsg class]) {
    defaultSysMsgInstance = [[SysMsg alloc] init];
  }
}
+ (SysMsg*) defaultInstance {
  return defaultSysMsgInstance;
}
- (SysMsg*) defaultInstance {
  return defaultSysMsgInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasJobServerId) {
    [output writeInt32:1 value:self.jobServerId];
  }
  if (self.hasTimestamp) {
    [output writeInt64:2 value:self.timestamp];
  }
  if (self.hasStartDate) {
    [output writeString:3 value:self.startDate];
  }
  if (self.hasEndDate) {
    [output writeString:4 value:self.endDate];
  }
  if (self.hasDisplayType) {
    [output writeInt32:5 value:self.displayType];
  }
  if (self.hasTitle) {
    [output writeString:6 value:self.title];
  }
  if (self.hasContent) {
    [output writeString:7 value:self.content];
  }
  if (self.hasFrequency) {
    [output writeInt32:8 value:self.frequency];
  }
  if (self.hasMsgType) {
    [output writeInt32:9 value:self.msgType];
  }
  if (self.hasNetType) {
    [output writeInt32:10 value:self.netType];
  }
  if (self.hasUrlDetail) {
    [output writeString:11 value:self.urlDetail];
  }
  if (self.hasImgLogo) {
    [output writeString:12 value:self.imgLogo];
  }
  if (self.hasImgTitleUrl) {
    [output writeString:13 value:self.imgTitleUrl];
  }
  if (self.hasImgContentUrl1) {
    [output writeString:14 value:self.imgContentUrl1];
  }
  if (self.hasImgContentUrl2) {
    [output writeString:15 value:self.imgContentUrl2];
  }
  if (self.hasImgContentUrl3) {
    [output writeString:16 value:self.imgContentUrl3];
  }
  if (self.hasReadAmount) {
    [output writeString:17 value:self.readAmount];
  }
  if (self.hasRandom) {
    [output writeInt32:18 value:self.random];
  }
  if (self.hasMemberType) {
    [output writeInt32:19 value:self.memberType];
  }
  if (self.hasIsTop) {
    [output writeInt32:20 value:self.isTop];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasJobServerId) {
    size += computeInt32Size(1, self.jobServerId);
  }
  if (self.hasTimestamp) {
    size += computeInt64Size(2, self.timestamp);
  }
  if (self.hasStartDate) {
    size += computeStringSize(3, self.startDate);
  }
  if (self.hasEndDate) {
    size += computeStringSize(4, self.endDate);
  }
  if (self.hasDisplayType) {
    size += computeInt32Size(5, self.displayType);
  }
  if (self.hasTitle) {
    size += computeStringSize(6, self.title);
  }
  if (self.hasContent) {
    size += computeStringSize(7, self.content);
  }
  if (self.hasFrequency) {
    size += computeInt32Size(8, self.frequency);
  }
  if (self.hasMsgType) {
    size += computeInt32Size(9, self.msgType);
  }
  if (self.hasNetType) {
    size += computeInt32Size(10, self.netType);
  }
  if (self.hasUrlDetail) {
    size += computeStringSize(11, self.urlDetail);
  }
  if (self.hasImgLogo) {
    size += computeStringSize(12, self.imgLogo);
  }
  if (self.hasImgTitleUrl) {
    size += computeStringSize(13, self.imgTitleUrl);
  }
  if (self.hasImgContentUrl1) {
    size += computeStringSize(14, self.imgContentUrl1);
  }
  if (self.hasImgContentUrl2) {
    size += computeStringSize(15, self.imgContentUrl2);
  }
  if (self.hasImgContentUrl3) {
    size += computeStringSize(16, self.imgContentUrl3);
  }
  if (self.hasReadAmount) {
    size += computeStringSize(17, self.readAmount);
  }
  if (self.hasRandom) {
    size += computeInt32Size(18, self.random);
  }
  if (self.hasMemberType) {
    size += computeInt32Size(19, self.memberType);
  }
  if (self.hasIsTop) {
    size += computeInt32Size(20, self.isTop);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (SysMsg*) parseFromData:(NSData*) data {
  return (SysMsg*)[[[SysMsg builder] mergeFromData:data] build];
}
+ (SysMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SysMsg*)[[[SysMsg builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SysMsg*) parseFromInputStream:(NSInputStream*) input {
  return (SysMsg*)[[[SysMsg builder] mergeFromInputStream:input] build];
}
+ (SysMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SysMsg*)[[[SysMsg builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SysMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SysMsg*)[[[SysMsg builder] mergeFromCodedInputStream:input] build];
}
+ (SysMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SysMsg*)[[[SysMsg builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SysMsg_Builder*) builder {
  return [[[SysMsg_Builder alloc] init] autorelease];
}
+ (SysMsg_Builder*) builderWithPrototype:(SysMsg*) prototype {
  return [[SysMsg builder] mergeFrom:prototype];
}
- (SysMsg_Builder*) builder {
  return [SysMsg builder];
}
@end

@interface SysMsg_Builder()
@property (retain) SysMsg* result;
@end

@implementation SysMsg_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[SysMsg alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (SysMsg_Builder*) clear {
  self.result = [[[SysMsg alloc] init] autorelease];
  return self;
}
- (SysMsg_Builder*) clone {
  return [SysMsg builderWithPrototype:result];
}
- (SysMsg*) defaultInstance {
  return [SysMsg defaultInstance];
}
- (SysMsg*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SysMsg*) buildPartial {
  SysMsg* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (SysMsg_Builder*) mergeFrom:(SysMsg*) other {
  if (other == [SysMsg defaultInstance]) {
    return self;
  }
  if (other.hasJobServerId) {
    [self setJobServerId:other.jobServerId];
  }
  if (other.hasTimestamp) {
    [self setTimestamp:other.timestamp];
  }
  if (other.hasStartDate) {
    [self setStartDate:other.startDate];
  }
  if (other.hasEndDate) {
    [self setEndDate:other.endDate];
  }
  if (other.hasDisplayType) {
    [self setDisplayType:other.displayType];
  }
  if (other.hasTitle) {
    [self setTitle:other.title];
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  if (other.hasFrequency) {
    [self setFrequency:other.frequency];
  }
  if (other.hasMsgType) {
    [self setMsgType:other.msgType];
  }
  if (other.hasNetType) {
    [self setNetType:other.netType];
  }
  if (other.hasUrlDetail) {
    [self setUrlDetail:other.urlDetail];
  }
  if (other.hasImgLogo) {
    [self setImgLogo:other.imgLogo];
  }
  if (other.hasImgTitleUrl) {
    [self setImgTitleUrl:other.imgTitleUrl];
  }
  if (other.hasImgContentUrl1) {
    [self setImgContentUrl1:other.imgContentUrl1];
  }
  if (other.hasImgContentUrl2) {
    [self setImgContentUrl2:other.imgContentUrl2];
  }
  if (other.hasImgContentUrl3) {
    [self setImgContentUrl3:other.imgContentUrl3];
  }
  if (other.hasReadAmount) {
    [self setReadAmount:other.readAmount];
  }
  if (other.hasRandom) {
    [self setRandom:other.random];
  }
  if (other.hasMemberType) {
    [self setMemberType:other.memberType];
  }
  if (other.hasIsTop) {
    [self setIsTop:other.isTop];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SysMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SysMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setJobServerId:[input readInt32]];
        break;
      }
      case 16: {
        [self setTimestamp:[input readInt64]];
        break;
      }
      case 26: {
        [self setStartDate:[input readString]];
        break;
      }
      case 34: {
        [self setEndDate:[input readString]];
        break;
      }
      case 40: {
        [self setDisplayType:[input readInt32]];
        break;
      }
      case 50: {
        [self setTitle:[input readString]];
        break;
      }
      case 58: {
        [self setContent:[input readString]];
        break;
      }
      case 64: {
        [self setFrequency:[input readInt32]];
        break;
      }
      case 72: {
        [self setMsgType:[input readInt32]];
        break;
      }
      case 80: {
        [self setNetType:[input readInt32]];
        break;
      }
      case 90: {
        [self setUrlDetail:[input readString]];
        break;
      }
      case 98: {
        [self setImgLogo:[input readString]];
        break;
      }
      case 106: {
        [self setImgTitleUrl:[input readString]];
        break;
      }
      case 114: {
        [self setImgContentUrl1:[input readString]];
        break;
      }
      case 122: {
        [self setImgContentUrl2:[input readString]];
        break;
      }
      case 130: {
        [self setImgContentUrl3:[input readString]];
        break;
      }
      case 138: {
        [self setReadAmount:[input readString]];
        break;
      }
      case 144: {
        [self setRandom:[input readInt32]];
        break;
      }
      case 152: {
        [self setMemberType:[input readInt32]];
        break;
      }
      case 160: {
        [self setIsTop:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasJobServerId {
  return result.hasJobServerId;
}
- (int32_t) jobServerId {
  return result.jobServerId;
}
- (SysMsg_Builder*) setJobServerId:(int32_t) value {
  result.hasJobServerId = YES;
  result.jobServerId = value;
  return self;
}
- (SysMsg_Builder*) clearJobServerId {
  result.hasJobServerId = NO;
  result.jobServerId = 0;
  return self;
}
- (BOOL) hasTimestamp {
  return result.hasTimestamp;
}
- (int64_t) timestamp {
  return result.timestamp;
}
- (SysMsg_Builder*) setTimestamp:(int64_t) value {
  result.hasTimestamp = YES;
  result.timestamp = value;
  return self;
}
- (SysMsg_Builder*) clearTimestamp {
  result.hasTimestamp = NO;
  result.timestamp = 0L;
  return self;
}
- (BOOL) hasStartDate {
  return result.hasStartDate;
}
- (NSString*) startDate {
  return result.startDate;
}
- (SysMsg_Builder*) setStartDate:(NSString*) value {
  result.hasStartDate = YES;
  result.startDate = value;
  return self;
}
- (SysMsg_Builder*) clearStartDate {
  result.hasStartDate = NO;
  result.startDate = @"";
  return self;
}
- (BOOL) hasEndDate {
  return result.hasEndDate;
}
- (NSString*) endDate {
  return result.endDate;
}
- (SysMsg_Builder*) setEndDate:(NSString*) value {
  result.hasEndDate = YES;
  result.endDate = value;
  return self;
}
- (SysMsg_Builder*) clearEndDate {
  result.hasEndDate = NO;
  result.endDate = @"";
  return self;
}
- (BOOL) hasDisplayType {
  return result.hasDisplayType;
}
- (int32_t) displayType {
  return result.displayType;
}
- (SysMsg_Builder*) setDisplayType:(int32_t) value {
  result.hasDisplayType = YES;
  result.displayType = value;
  return self;
}
- (SysMsg_Builder*) clearDisplayType {
  result.hasDisplayType = NO;
  result.displayType = 0;
  return self;
}
- (BOOL) hasTitle {
  return result.hasTitle;
}
- (NSString*) title {
  return result.title;
}
- (SysMsg_Builder*) setTitle:(NSString*) value {
  result.hasTitle = YES;
  result.title = value;
  return self;
}
- (SysMsg_Builder*) clearTitle {
  result.hasTitle = NO;
  result.title = @"";
  return self;
}
- (BOOL) hasContent {
  return result.hasContent;
}
- (NSString*) content {
  return result.content;
}
- (SysMsg_Builder*) setContent:(NSString*) value {
  result.hasContent = YES;
  result.content = value;
  return self;
}
- (SysMsg_Builder*) clearContent {
  result.hasContent = NO;
  result.content = @"";
  return self;
}
- (BOOL) hasFrequency {
  return result.hasFrequency;
}
- (int32_t) frequency {
  return result.frequency;
}
- (SysMsg_Builder*) setFrequency:(int32_t) value {
  result.hasFrequency = YES;
  result.frequency = value;
  return self;
}
- (SysMsg_Builder*) clearFrequency {
  result.hasFrequency = NO;
  result.frequency = 0;
  return self;
}
- (BOOL) hasMsgType {
  return result.hasMsgType;
}
- (int32_t) msgType {
  return result.msgType;
}
- (SysMsg_Builder*) setMsgType:(int32_t) value {
  result.hasMsgType = YES;
  result.msgType = value;
  return self;
}
- (SysMsg_Builder*) clearMsgType {
  result.hasMsgType = NO;
  result.msgType = 0;
  return self;
}
- (BOOL) hasNetType {
  return result.hasNetType;
}
- (int32_t) netType {
  return result.netType;
}
- (SysMsg_Builder*) setNetType:(int32_t) value {
  result.hasNetType = YES;
  result.netType = value;
  return self;
}
- (SysMsg_Builder*) clearNetType {
  result.hasNetType = NO;
  result.netType = 0;
  return self;
}
- (BOOL) hasUrlDetail {
  return result.hasUrlDetail;
}
- (NSString*) urlDetail {
  return result.urlDetail;
}
- (SysMsg_Builder*) setUrlDetail:(NSString*) value {
  result.hasUrlDetail = YES;
  result.urlDetail = value;
  return self;
}
- (SysMsg_Builder*) clearUrlDetail {
  result.hasUrlDetail = NO;
  result.urlDetail = @"";
  return self;
}
- (BOOL) hasImgLogo {
  return result.hasImgLogo;
}
- (NSString*) imgLogo {
  return result.imgLogo;
}
- (SysMsg_Builder*) setImgLogo:(NSString*) value {
  result.hasImgLogo = YES;
  result.imgLogo = value;
  return self;
}
- (SysMsg_Builder*) clearImgLogo {
  result.hasImgLogo = NO;
  result.imgLogo = @"";
  return self;
}
- (BOOL) hasImgTitleUrl {
  return result.hasImgTitleUrl;
}
- (NSString*) imgTitleUrl {
  return result.imgTitleUrl;
}
- (SysMsg_Builder*) setImgTitleUrl:(NSString*) value {
  result.hasImgTitleUrl = YES;
  result.imgTitleUrl = value;
  return self;
}
- (SysMsg_Builder*) clearImgTitleUrl {
  result.hasImgTitleUrl = NO;
  result.imgTitleUrl = @"";
  return self;
}
- (BOOL) hasImgContentUrl1 {
  return result.hasImgContentUrl1;
}
- (NSString*) imgContentUrl1 {
  return result.imgContentUrl1;
}
- (SysMsg_Builder*) setImgContentUrl1:(NSString*) value {
  result.hasImgContentUrl1 = YES;
  result.imgContentUrl1 = value;
  return self;
}
- (SysMsg_Builder*) clearImgContentUrl1 {
  result.hasImgContentUrl1 = NO;
  result.imgContentUrl1 = @"";
  return self;
}
- (BOOL) hasImgContentUrl2 {
  return result.hasImgContentUrl2;
}
- (NSString*) imgContentUrl2 {
  return result.imgContentUrl2;
}
- (SysMsg_Builder*) setImgContentUrl2:(NSString*) value {
  result.hasImgContentUrl2 = YES;
  result.imgContentUrl2 = value;
  return self;
}
- (SysMsg_Builder*) clearImgContentUrl2 {
  result.hasImgContentUrl2 = NO;
  result.imgContentUrl2 = @"";
  return self;
}
- (BOOL) hasImgContentUrl3 {
  return result.hasImgContentUrl3;
}
- (NSString*) imgContentUrl3 {
  return result.imgContentUrl3;
}
- (SysMsg_Builder*) setImgContentUrl3:(NSString*) value {
  result.hasImgContentUrl3 = YES;
  result.imgContentUrl3 = value;
  return self;
}
- (SysMsg_Builder*) clearImgContentUrl3 {
  result.hasImgContentUrl3 = NO;
  result.imgContentUrl3 = @"";
  return self;
}
- (BOOL) hasReadAmount {
  return result.hasReadAmount;
}
- (NSString*) readAmount {
  return result.readAmount;
}
- (SysMsg_Builder*) setReadAmount:(NSString*) value {
  result.hasReadAmount = YES;
  result.readAmount = value;
  return self;
}
- (SysMsg_Builder*) clearReadAmount {
  result.hasReadAmount = NO;
  result.readAmount = @"";
  return self;
}
- (BOOL) hasRandom {
  return result.hasRandom;
}
- (int32_t) random {
  return result.random;
}
- (SysMsg_Builder*) setRandom:(int32_t) value {
  result.hasRandom = YES;
  result.random = value;
  return self;
}
- (SysMsg_Builder*) clearRandom {
  result.hasRandom = NO;
  result.random = 0;
  return self;
}
- (BOOL) hasMemberType {
  return result.hasMemberType;
}
- (int32_t) memberType {
  return result.memberType;
}
- (SysMsg_Builder*) setMemberType:(int32_t) value {
  result.hasMemberType = YES;
  result.memberType = value;
  return self;
}
- (SysMsg_Builder*) clearMemberType {
  result.hasMemberType = NO;
  result.memberType = 0;
  return self;
}
- (BOOL) hasIsTop {
  return result.hasIsTop;
}
- (int32_t) isTop {
  return result.isTop;
}
- (SysMsg_Builder*) setIsTop:(int32_t) value {
  result.hasIsTop = YES;
  result.isTop = value;
  return self;
}
- (SysMsg_Builder*) clearIsTop {
  result.hasIsTop = NO;
  result.isTop = 0;
  return self;
}
@end

@interface RequestSysMsg ()
@property int32_t jobServerId;
@property int64_t timestamp;
@end

@implementation RequestSysMsg

- (BOOL) hasJobServerId {
  return !!hasJobServerId_;
}
- (void) setHasJobServerId:(BOOL) value {
  hasJobServerId_ = !!value;
}
@synthesize jobServerId;
- (BOOL) hasTimestamp {
  return !!hasTimestamp_;
}
- (void) setHasTimestamp:(BOOL) value {
  hasTimestamp_ = !!value;
}
@synthesize timestamp;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.jobServerId = 0;
    self.timestamp = 0L;
  }
  return self;
}
static RequestSysMsg* defaultRequestSysMsgInstance = nil;
+ (void) initialize {
  if (self == [RequestSysMsg class]) {
    defaultRequestSysMsgInstance = [[RequestSysMsg alloc] init];
  }
}
+ (RequestSysMsg*) defaultInstance {
  return defaultRequestSysMsgInstance;
}
- (RequestSysMsg*) defaultInstance {
  return defaultRequestSysMsgInstance;
}
- (BOOL) isInitialized {
  if (!self.hasJobServerId) {
    return NO;
  }
  if (!self.hasTimestamp) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasJobServerId) {
    [output writeInt32:1 value:self.jobServerId];
  }
  if (self.hasTimestamp) {
    [output writeInt64:2 value:self.timestamp];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasJobServerId) {
    size += computeInt32Size(1, self.jobServerId);
  }
  if (self.hasTimestamp) {
    size += computeInt64Size(2, self.timestamp);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (RequestSysMsg*) parseFromData:(NSData*) data {
  return (RequestSysMsg*)[[[RequestSysMsg builder] mergeFromData:data] build];
}
+ (RequestSysMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestSysMsg*)[[[RequestSysMsg builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RequestSysMsg*) parseFromInputStream:(NSInputStream*) input {
  return (RequestSysMsg*)[[[RequestSysMsg builder] mergeFromInputStream:input] build];
}
+ (RequestSysMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestSysMsg*)[[[RequestSysMsg builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestSysMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RequestSysMsg*)[[[RequestSysMsg builder] mergeFromCodedInputStream:input] build];
}
+ (RequestSysMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RequestSysMsg*)[[[RequestSysMsg builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RequestSysMsg_Builder*) builder {
  return [[[RequestSysMsg_Builder alloc] init] autorelease];
}
+ (RequestSysMsg_Builder*) builderWithPrototype:(RequestSysMsg*) prototype {
  return [[RequestSysMsg builder] mergeFrom:prototype];
}
- (RequestSysMsg_Builder*) builder {
  return [RequestSysMsg builder];
}
@end

@interface RequestSysMsg_Builder()
@property (retain) RequestSysMsg* result;
@end

@implementation RequestSysMsg_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RequestSysMsg alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RequestSysMsg_Builder*) clear {
  self.result = [[[RequestSysMsg alloc] init] autorelease];
  return self;
}
- (RequestSysMsg_Builder*) clone {
  return [RequestSysMsg builderWithPrototype:result];
}
- (RequestSysMsg*) defaultInstance {
  return [RequestSysMsg defaultInstance];
}
- (RequestSysMsg*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RequestSysMsg*) buildPartial {
  RequestSysMsg* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RequestSysMsg_Builder*) mergeFrom:(RequestSysMsg*) other {
  if (other == [RequestSysMsg defaultInstance]) {
    return self;
  }
  if (other.hasJobServerId) {
    [self setJobServerId:other.jobServerId];
  }
  if (other.hasTimestamp) {
    [self setTimestamp:other.timestamp];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RequestSysMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RequestSysMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setJobServerId:[input readInt32]];
        break;
      }
      case 16: {
        [self setTimestamp:[input readInt64]];
        break;
      }
    }
  }
}
- (BOOL) hasJobServerId {
  return result.hasJobServerId;
}
- (int32_t) jobServerId {
  return result.jobServerId;
}
- (RequestSysMsg_Builder*) setJobServerId:(int32_t) value {
  result.hasJobServerId = YES;
  result.jobServerId = value;
  return self;
}
- (RequestSysMsg_Builder*) clearJobServerId {
  result.hasJobServerId = NO;
  result.jobServerId = 0;
  return self;
}
- (BOOL) hasTimestamp {
  return result.hasTimestamp;
}
- (int64_t) timestamp {
  return result.timestamp;
}
- (RequestSysMsg_Builder*) setTimestamp:(int64_t) value {
  result.hasTimestamp = YES;
  result.timestamp = value;
  return self;
}
- (RequestSysMsg_Builder*) clearTimestamp {
  result.hasTimestamp = NO;
  result.timestamp = 0L;
  return self;
}
@end

@interface GetSysMsgRequest ()
@property (retain) NSString* mobileNum;
@property (retain) NSString* imsi;
@property (retain) NSString* mobileManufacturer;
@property (retain) NSString* mobileType;
@property (retain) NSMutableArray* mutableMessagesList;
@property Platform platform;
@property int32_t member;
@end

@implementation GetSysMsgRequest

- (BOOL) hasMobileNum {
  return !!hasMobileNum_;
}
- (void) setHasMobileNum:(BOOL) value {
  hasMobileNum_ = !!value;
}
@synthesize mobileNum;
- (BOOL) hasImsi {
  return !!hasImsi_;
}
- (void) setHasImsi:(BOOL) value {
  hasImsi_ = !!value;
}
@synthesize imsi;
- (BOOL) hasMobileManufacturer {
  return !!hasMobileManufacturer_;
}
- (void) setHasMobileManufacturer:(BOOL) value {
  hasMobileManufacturer_ = !!value;
}
@synthesize mobileManufacturer;
- (BOOL) hasMobileType {
  return !!hasMobileType_;
}
- (void) setHasMobileType:(BOOL) value {
  hasMobileType_ = !!value;
}
@synthesize mobileType;
@synthesize mutableMessagesList;
- (BOOL) hasPlatform {
  return !!hasPlatform_;
}
- (void) setHasPlatform:(BOOL) value {
  hasPlatform_ = !!value;
}
@synthesize platform;
- (BOOL) hasMember {
  return !!hasMember_;
}
- (void) setHasMember:(BOOL) value {
  hasMember_ = !!value;
}
@synthesize member;
- (void) dealloc {
  self.mobileNum = nil;
  self.imsi = nil;
  self.mobileManufacturer = nil;
  self.mobileType = nil;
  self.mutableMessagesList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.mobileNum = @"";
    self.imsi = @"";
    self.mobileManufacturer = @"";
    self.mobileType = @"";
    self.platform = PlatformNone;
    self.member = 0;
  }
  return self;
}
static GetSysMsgRequest* defaultGetSysMsgRequestInstance = nil;
+ (void) initialize {
  if (self == [GetSysMsgRequest class]) {
    defaultGetSysMsgRequestInstance = [[GetSysMsgRequest alloc] init];
  }
}
+ (GetSysMsgRequest*) defaultInstance {
  return defaultGetSysMsgRequestInstance;
}
- (GetSysMsgRequest*) defaultInstance {
  return defaultGetSysMsgRequestInstance;
}
- (NSArray*) messagesList {
  return mutableMessagesList;
}
- (RequestSysMsg*) messagesAtIndex:(int32_t) index {
  id value = [mutableMessagesList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  for (RequestSysMsg* element in self.messagesList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasMobileNum) {
    [output writeString:1 value:self.mobileNum];
  }
  if (self.hasImsi) {
    [output writeString:2 value:self.imsi];
  }
  if (self.hasMobileManufacturer) {
    [output writeString:3 value:self.mobileManufacturer];
  }
  if (self.hasMobileType) {
    [output writeString:4 value:self.mobileType];
  }
  for (RequestSysMsg* element in self.messagesList) {
    [output writeMessage:5 value:element];
  }
  if (self.hasPlatform) {
    [output writeEnum:6 value:self.platform];
  }
  if (self.hasMember) {
    [output writeInt32:7 value:self.member];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasMobileNum) {
    size += computeStringSize(1, self.mobileNum);
  }
  if (self.hasImsi) {
    size += computeStringSize(2, self.imsi);
  }
  if (self.hasMobileManufacturer) {
    size += computeStringSize(3, self.mobileManufacturer);
  }
  if (self.hasMobileType) {
    size += computeStringSize(4, self.mobileType);
  }
  for (RequestSysMsg* element in self.messagesList) {
    size += computeMessageSize(5, element);
  }
  if (self.hasPlatform) {
    size += computeEnumSize(6, self.platform);
  }
  if (self.hasMember) {
    size += computeInt32Size(7, self.member);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (GetSysMsgRequest*) parseFromData:(NSData*) data {
  return (GetSysMsgRequest*)[[[GetSysMsgRequest builder] mergeFromData:data] build];
}
+ (GetSysMsgRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetSysMsgRequest*)[[[GetSysMsgRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (GetSysMsgRequest*) parseFromInputStream:(NSInputStream*) input {
  return (GetSysMsgRequest*)[[[GetSysMsgRequest builder] mergeFromInputStream:input] build];
}
+ (GetSysMsgRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetSysMsgRequest*)[[[GetSysMsgRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetSysMsgRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (GetSysMsgRequest*)[[[GetSysMsgRequest builder] mergeFromCodedInputStream:input] build];
}
+ (GetSysMsgRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetSysMsgRequest*)[[[GetSysMsgRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetSysMsgRequest_Builder*) builder {
  return [[[GetSysMsgRequest_Builder alloc] init] autorelease];
}
+ (GetSysMsgRequest_Builder*) builderWithPrototype:(GetSysMsgRequest*) prototype {
  return [[GetSysMsgRequest builder] mergeFrom:prototype];
}
- (GetSysMsgRequest_Builder*) builder {
  return [GetSysMsgRequest builder];
}
@end

@interface GetSysMsgRequest_Builder()
@property (retain) GetSysMsgRequest* result;
@end

@implementation GetSysMsgRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[GetSysMsgRequest alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (GetSysMsgRequest_Builder*) clear {
  self.result = [[[GetSysMsgRequest alloc] init] autorelease];
  return self;
}
- (GetSysMsgRequest_Builder*) clone {
  return [GetSysMsgRequest builderWithPrototype:result];
}
- (GetSysMsgRequest*) defaultInstance {
  return [GetSysMsgRequest defaultInstance];
}
- (GetSysMsgRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (GetSysMsgRequest*) buildPartial {
  GetSysMsgRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (GetSysMsgRequest_Builder*) mergeFrom:(GetSysMsgRequest*) other {
  if (other == [GetSysMsgRequest defaultInstance]) {
    return self;
  }
  if (other.hasMobileNum) {
    [self setMobileNum:other.mobileNum];
  }
  if (other.hasImsi) {
    [self setImsi:other.imsi];
  }
  if (other.hasMobileManufacturer) {
    [self setMobileManufacturer:other.mobileManufacturer];
  }
  if (other.hasMobileType) {
    [self setMobileType:other.mobileType];
  }
  if (other.mutableMessagesList.count > 0) {
    if (result.mutableMessagesList == nil) {
      result.mutableMessagesList = [NSMutableArray array];
    }
    [result.mutableMessagesList addObjectsFromArray:other.mutableMessagesList];
  }
  if (other.hasPlatform) {
    [self setPlatform:other.platform];
  }
  if (other.hasMember) {
    [self setMember:other.member];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (GetSysMsgRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (GetSysMsgRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setMobileNum:[input readString]];
        break;
      }
      case 18: {
        [self setImsi:[input readString]];
        break;
      }
      case 26: {
        [self setMobileManufacturer:[input readString]];
        break;
      }
      case 34: {
        [self setMobileType:[input readString]];
        break;
      }
      case 42: {
        RequestSysMsg_Builder* subBuilder = [RequestSysMsg builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addMessages:[subBuilder buildPartial]];
        break;
      }
      case 48: {
        int32_t value = [input readEnum];
        if (PlatformIsValidValue(value)) {
          [self setPlatform:value];
        } else {
          [unknownFields mergeVarintField:6 value:value];
        }
        break;
      }
      case 56: {
        [self setMember:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasMobileNum {
  return result.hasMobileNum;
}
- (NSString*) mobileNum {
  return result.mobileNum;
}
- (GetSysMsgRequest_Builder*) setMobileNum:(NSString*) value {
  result.hasMobileNum = YES;
  result.mobileNum = value;
  return self;
}
- (GetSysMsgRequest_Builder*) clearMobileNum {
  result.hasMobileNum = NO;
  result.mobileNum = @"";
  return self;
}
- (BOOL) hasImsi {
  return result.hasImsi;
}
- (NSString*) imsi {
  return result.imsi;
}
- (GetSysMsgRequest_Builder*) setImsi:(NSString*) value {
  result.hasImsi = YES;
  result.imsi = value;
  return self;
}
- (GetSysMsgRequest_Builder*) clearImsi {
  result.hasImsi = NO;
  result.imsi = @"";
  return self;
}
- (BOOL) hasMobileManufacturer {
  return result.hasMobileManufacturer;
}
- (NSString*) mobileManufacturer {
  return result.mobileManufacturer;
}
- (GetSysMsgRequest_Builder*) setMobileManufacturer:(NSString*) value {
  result.hasMobileManufacturer = YES;
  result.mobileManufacturer = value;
  return self;
}
- (GetSysMsgRequest_Builder*) clearMobileManufacturer {
  result.hasMobileManufacturer = NO;
  result.mobileManufacturer = @"";
  return self;
}
- (BOOL) hasMobileType {
  return result.hasMobileType;
}
- (NSString*) mobileType {
  return result.mobileType;
}
- (GetSysMsgRequest_Builder*) setMobileType:(NSString*) value {
  result.hasMobileType = YES;
  result.mobileType = value;
  return self;
}
- (GetSysMsgRequest_Builder*) clearMobileType {
  result.hasMobileType = NO;
  result.mobileType = @"";
  return self;
}
- (NSArray*) messagesList {
  if (result.mutableMessagesList == nil) { return [NSArray array]; }
  return result.mutableMessagesList;
}
- (RequestSysMsg*) messagesAtIndex:(int32_t) index {
  return [result messagesAtIndex:index];
}
- (GetSysMsgRequest_Builder*) replaceMessagesAtIndex:(int32_t) index with:(RequestSysMsg*) value {
  [result.mutableMessagesList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (GetSysMsgRequest_Builder*) addAllMessages:(NSArray*) values {
  if (result.mutableMessagesList == nil) {
    result.mutableMessagesList = [NSMutableArray array];
  }
  [result.mutableMessagesList addObjectsFromArray:values];
  return self;
}
- (GetSysMsgRequest_Builder*) clearMessagesList {
  result.mutableMessagesList = nil;
  return self;
}
- (GetSysMsgRequest_Builder*) addMessages:(RequestSysMsg*) value {
  if (result.mutableMessagesList == nil) {
    result.mutableMessagesList = [NSMutableArray array];
  }
  [result.mutableMessagesList addObject:value];
  return self;
}
- (BOOL) hasPlatform {
  return result.hasPlatform;
}
- (Platform) platform {
  return result.platform;
}
- (GetSysMsgRequest_Builder*) setPlatform:(Platform) value {
  result.hasPlatform = YES;
  result.platform = value;
  return self;
}
- (GetSysMsgRequest_Builder*) clearPlatform {
  result.hasPlatform = NO;
  result.platform = PlatformNone;
  return self;
}
- (BOOL) hasMember {
  return result.hasMember;
}
- (int32_t) member {
  return result.member;
}
- (GetSysMsgRequest_Builder*) setMember:(int32_t) value {
  result.hasMember = YES;
  result.member = value;
  return self;
}
- (GetSysMsgRequest_Builder*) clearMember {
  result.hasMember = NO;
  result.member = 0;
  return self;
}
@end

@interface GetSysMsgResponse ()
@property (retain) NSMutableArray* mutableMessagesList;
@property int32_t frequency;
@property (retain) NSString* loginfo;
@end

@implementation GetSysMsgResponse

@synthesize mutableMessagesList;
- (BOOL) hasFrequency {
  return !!hasFrequency_;
}
- (void) setHasFrequency:(BOOL) value {
  hasFrequency_ = !!value;
}
@synthesize frequency;
- (BOOL) hasLoginfo {
  return !!hasLoginfo_;
}
- (void) setHasLoginfo:(BOOL) value {
  hasLoginfo_ = !!value;
}
@synthesize loginfo;
- (void) dealloc {
  self.mutableMessagesList = nil;
  self.loginfo = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.frequency = 0;
    self.loginfo = @"";
  }
  return self;
}
static GetSysMsgResponse* defaultGetSysMsgResponseInstance = nil;
+ (void) initialize {
  if (self == [GetSysMsgResponse class]) {
    defaultGetSysMsgResponseInstance = [[GetSysMsgResponse alloc] init];
  }
}
+ (GetSysMsgResponse*) defaultInstance {
  return defaultGetSysMsgResponseInstance;
}
- (GetSysMsgResponse*) defaultInstance {
  return defaultGetSysMsgResponseInstance;
}
- (NSArray*) messagesList {
  return mutableMessagesList;
}
- (SysMsg*) messagesAtIndex:(int32_t) index {
  id value = [mutableMessagesList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (SysMsg* element in self.messagesList) {
    [output writeMessage:1 value:element];
  }
  if (self.hasFrequency) {
    [output writeInt32:2 value:self.frequency];
  }
  if (self.hasLoginfo) {
    [output writeString:10 value:self.loginfo];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (SysMsg* element in self.messagesList) {
    size += computeMessageSize(1, element);
  }
  if (self.hasFrequency) {
    size += computeInt32Size(2, self.frequency);
  }
  if (self.hasLoginfo) {
    size += computeStringSize(10, self.loginfo);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (GetSysMsgResponse*) parseFromData:(NSData*) data {
  return (GetSysMsgResponse*)[[[GetSysMsgResponse builder] mergeFromData:data] build];
}
+ (GetSysMsgResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetSysMsgResponse*)[[[GetSysMsgResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (GetSysMsgResponse*) parseFromInputStream:(NSInputStream*) input {
  return (GetSysMsgResponse*)[[[GetSysMsgResponse builder] mergeFromInputStream:input] build];
}
+ (GetSysMsgResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetSysMsgResponse*)[[[GetSysMsgResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetSysMsgResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (GetSysMsgResponse*)[[[GetSysMsgResponse builder] mergeFromCodedInputStream:input] build];
}
+ (GetSysMsgResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetSysMsgResponse*)[[[GetSysMsgResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetSysMsgResponse_Builder*) builder {
  return [[[GetSysMsgResponse_Builder alloc] init] autorelease];
}
+ (GetSysMsgResponse_Builder*) builderWithPrototype:(GetSysMsgResponse*) prototype {
  return [[GetSysMsgResponse builder] mergeFrom:prototype];
}
- (GetSysMsgResponse_Builder*) builder {
  return [GetSysMsgResponse builder];
}
@end

@interface GetSysMsgResponse_Builder()
@property (retain) GetSysMsgResponse* result;
@end

@implementation GetSysMsgResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[GetSysMsgResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (GetSysMsgResponse_Builder*) clear {
  self.result = [[[GetSysMsgResponse alloc] init] autorelease];
  return self;
}
- (GetSysMsgResponse_Builder*) clone {
  return [GetSysMsgResponse builderWithPrototype:result];
}
- (GetSysMsgResponse*) defaultInstance {
  return [GetSysMsgResponse defaultInstance];
}
- (GetSysMsgResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (GetSysMsgResponse*) buildPartial {
  GetSysMsgResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (GetSysMsgResponse_Builder*) mergeFrom:(GetSysMsgResponse*) other {
  if (other == [GetSysMsgResponse defaultInstance]) {
    return self;
  }
  if (other.mutableMessagesList.count > 0) {
    if (result.mutableMessagesList == nil) {
      result.mutableMessagesList = [NSMutableArray array];
    }
    [result.mutableMessagesList addObjectsFromArray:other.mutableMessagesList];
  }
  if (other.hasFrequency) {
    [self setFrequency:other.frequency];
  }
  if (other.hasLoginfo) {
    [self setLoginfo:other.loginfo];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (GetSysMsgResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (GetSysMsgResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        SysMsg_Builder* subBuilder = [SysMsg builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addMessages:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        [self setFrequency:[input readInt32]];
        break;
      }
      case 82: {
        [self setLoginfo:[input readString]];
        break;
      }
    }
  }
}
- (NSArray*) messagesList {
  if (result.mutableMessagesList == nil) { return [NSArray array]; }
  return result.mutableMessagesList;
}
- (SysMsg*) messagesAtIndex:(int32_t) index {
  return [result messagesAtIndex:index];
}
- (GetSysMsgResponse_Builder*) replaceMessagesAtIndex:(int32_t) index with:(SysMsg*) value {
  [result.mutableMessagesList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (GetSysMsgResponse_Builder*) addAllMessages:(NSArray*) values {
  if (result.mutableMessagesList == nil) {
    result.mutableMessagesList = [NSMutableArray array];
  }
  [result.mutableMessagesList addObjectsFromArray:values];
  return self;
}
- (GetSysMsgResponse_Builder*) clearMessagesList {
  result.mutableMessagesList = nil;
  return self;
}
- (GetSysMsgResponse_Builder*) addMessages:(SysMsg*) value {
  if (result.mutableMessagesList == nil) {
    result.mutableMessagesList = [NSMutableArray array];
  }
  [result.mutableMessagesList addObject:value];
  return self;
}
- (BOOL) hasFrequency {
  return result.hasFrequency;
}
- (int32_t) frequency {
  return result.frequency;
}
- (GetSysMsgResponse_Builder*) setFrequency:(int32_t) value {
  result.hasFrequency = YES;
  result.frequency = value;
  return self;
}
- (GetSysMsgResponse_Builder*) clearFrequency {
  result.hasFrequency = NO;
  result.frequency = 0;
  return self;
}
- (BOOL) hasLoginfo {
  return result.hasLoginfo;
}
- (NSString*) loginfo {
  return result.loginfo;
}
- (GetSysMsgResponse_Builder*) setLoginfo:(NSString*) value {
  result.hasLoginfo = YES;
  result.loginfo = value;
  return self;
}
- (GetSysMsgResponse_Builder*) clearLoginfo {
  result.hasLoginfo = NO;
  result.loginfo = @"";
  return self;
}
@end

