// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class QCategory;
@class QCategory_Builder;
@class QCity;
@class QCity_Builder;
@class QCompany;
@class QCompany_Builder;
@class QueryPublicInfoRequest;
@class QueryPublicInfoRequest_Builder;
@class QueryPublicInfoResponse;
@class QueryPublicInfoResponse_Builder;

@interface QueryPublicInfoProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface QCity : PBGeneratedMessage {
@private
  BOOL hasIsHot_:1;
  BOOL hasCityId_:1;
  BOOL hasCityName_:1;
  BOOL hasFirstWord_:1;
  BOOL isHot_:1;
  int32_t cityId;
  NSString* cityName;
  NSString* firstWord;
}
- (BOOL) hasCityId;
- (BOOL) hasCityName;
- (BOOL) hasIsHot;
- (BOOL) hasFirstWord;
@property (readonly) int32_t cityId;
@property (readonly, retain) NSString* cityName;
- (BOOL) isHot;
@property (readonly, retain) NSString* firstWord;

+ (QCity*) defaultInstance;
- (QCity*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QCity_Builder*) builder;
+ (QCity_Builder*) builder;
+ (QCity_Builder*) builderWithPrototype:(QCity*) prototype;

+ (QCity*) parseFromData:(NSData*) data;
+ (QCity*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QCity*) parseFromInputStream:(NSInputStream*) input;
+ (QCity*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QCity*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QCity*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QCity_Builder : PBGeneratedMessage_Builder {
@private
  QCity* result;
}

- (QCity*) defaultInstance;

- (QCity_Builder*) clear;
- (QCity_Builder*) clone;

- (QCity*) build;
- (QCity*) buildPartial;

- (QCity_Builder*) mergeFrom:(QCity*) other;
- (QCity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QCity_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCityId;
- (int32_t) cityId;
- (QCity_Builder*) setCityId:(int32_t) value;
- (QCity_Builder*) clearCityId;

- (BOOL) hasCityName;
- (NSString*) cityName;
- (QCity_Builder*) setCityName:(NSString*) value;
- (QCity_Builder*) clearCityName;

- (BOOL) hasIsHot;
- (BOOL) isHot;
- (QCity_Builder*) setIsHot:(BOOL) value;
- (QCity_Builder*) clearIsHot;

- (BOOL) hasFirstWord;
- (NSString*) firstWord;
- (QCity_Builder*) setFirstWord:(NSString*) value;
- (QCity_Builder*) clearFirstWord;
@end

@interface QCategory : PBGeneratedMessage {
@private
  BOOL hasCategoryId_:1;
  BOOL hasCategoryName_:1;
  int32_t categoryId;
  NSString* categoryName;
}
- (BOOL) hasCategoryId;
- (BOOL) hasCategoryName;
@property (readonly) int32_t categoryId;
@property (readonly, retain) NSString* categoryName;

+ (QCategory*) defaultInstance;
- (QCategory*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QCategory_Builder*) builder;
+ (QCategory_Builder*) builder;
+ (QCategory_Builder*) builderWithPrototype:(QCategory*) prototype;

+ (QCategory*) parseFromData:(NSData*) data;
+ (QCategory*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QCategory*) parseFromInputStream:(NSInputStream*) input;
+ (QCategory*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QCategory*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QCategory*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QCategory_Builder : PBGeneratedMessage_Builder {
@private
  QCategory* result;
}

- (QCategory*) defaultInstance;

- (QCategory_Builder*) clear;
- (QCategory_Builder*) clone;

- (QCategory*) build;
- (QCategory*) buildPartial;

- (QCategory_Builder*) mergeFrom:(QCategory*) other;
- (QCategory_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QCategory_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCategoryId;
- (int32_t) categoryId;
- (QCategory_Builder*) setCategoryId:(int32_t) value;
- (QCategory_Builder*) clearCategoryId;

- (BOOL) hasCategoryName;
- (NSString*) categoryName;
- (QCategory_Builder*) setCategoryName:(NSString*) value;
- (QCategory_Builder*) clearCategoryName;
@end

@interface QCompany : PBGeneratedMessage {
@private
  BOOL hasGpsx_:1;
  BOOL hasGpsy_:1;
  BOOL hasCompanyId_:1;
  BOOL hasCompanyName_:1;
  BOOL hasCompamyTel_:1;
  BOOL hasCompanyAdd_:1;
  BOOL hasCompanyDescription_:1;
  BOOL hasCompanyPicUrl_:1;
  Float32 gpsx;
  Float32 gpsy;
  NSString* companyId;
  NSString* companyName;
  NSString* compamyTel;
  NSString* companyAdd;
  NSString* companyDescription;
  NSString* companyPicUrl;
}
- (BOOL) hasCompanyId;
- (BOOL) hasCompanyName;
- (BOOL) hasCompamyTel;
- (BOOL) hasCompanyAdd;
- (BOOL) hasCompanyDescription;
- (BOOL) hasCompanyPicUrl;
- (BOOL) hasGpsx;
- (BOOL) hasGpsy;
@property (readonly, retain) NSString* companyId;
@property (readonly, retain) NSString* companyName;
@property (readonly, retain) NSString* compamyTel;
@property (readonly, retain) NSString* companyAdd;
@property (readonly, retain) NSString* companyDescription;
@property (readonly, retain) NSString* companyPicUrl;
@property (readonly) Float32 gpsx;
@property (readonly) Float32 gpsy;

+ (QCompany*) defaultInstance;
- (QCompany*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QCompany_Builder*) builder;
+ (QCompany_Builder*) builder;
+ (QCompany_Builder*) builderWithPrototype:(QCompany*) prototype;

+ (QCompany*) parseFromData:(NSData*) data;
+ (QCompany*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QCompany*) parseFromInputStream:(NSInputStream*) input;
+ (QCompany*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QCompany*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QCompany*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QCompany_Builder : PBGeneratedMessage_Builder {
@private
  QCompany* result;
}

- (QCompany*) defaultInstance;

- (QCompany_Builder*) clear;
- (QCompany_Builder*) clone;

- (QCompany*) build;
- (QCompany*) buildPartial;

- (QCompany_Builder*) mergeFrom:(QCompany*) other;
- (QCompany_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QCompany_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCompanyId;
- (NSString*) companyId;
- (QCompany_Builder*) setCompanyId:(NSString*) value;
- (QCompany_Builder*) clearCompanyId;

- (BOOL) hasCompanyName;
- (NSString*) companyName;
- (QCompany_Builder*) setCompanyName:(NSString*) value;
- (QCompany_Builder*) clearCompanyName;

- (BOOL) hasCompamyTel;
- (NSString*) compamyTel;
- (QCompany_Builder*) setCompamyTel:(NSString*) value;
- (QCompany_Builder*) clearCompamyTel;

- (BOOL) hasCompanyAdd;
- (NSString*) companyAdd;
- (QCompany_Builder*) setCompanyAdd:(NSString*) value;
- (QCompany_Builder*) clearCompanyAdd;

- (BOOL) hasCompanyDescription;
- (NSString*) companyDescription;
- (QCompany_Builder*) setCompanyDescription:(NSString*) value;
- (QCompany_Builder*) clearCompanyDescription;

- (BOOL) hasCompanyPicUrl;
- (NSString*) companyPicUrl;
- (QCompany_Builder*) setCompanyPicUrl:(NSString*) value;
- (QCompany_Builder*) clearCompanyPicUrl;

- (BOOL) hasGpsx;
- (Float32) gpsx;
- (QCompany_Builder*) setGpsx:(Float32) value;
- (QCompany_Builder*) clearGpsx;

- (BOOL) hasGpsy;
- (Float32) gpsy;
- (QCompany_Builder*) setGpsy:(Float32) value;
- (QCompany_Builder*) clearGpsy;
@end

@interface QueryPublicInfoRequest : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasCityId_:1;
  BOOL hasStart_:1;
  BOOL hasRows_:1;
  BOOL hasKeyword_:1;
  BOOL hasMobileNum_:1;
  BOOL hasImsi_:1;
  BOOL hasMobileManufacturer_:1;
  BOOL hasMobileType_:1;
  int32_t type;
  int32_t cityId;
  int32_t start;
  int32_t rows;
  NSString* keyword;
  NSString* mobileNum;
  NSString* imsi;
  NSString* mobileManufacturer;
  NSString* mobileType;
  NSMutableArray* mutableCategoryIdsList;
  NSMutableArray* mutableCompanyIdsList;
}
- (BOOL) hasType;
- (BOOL) hasCityId;
- (BOOL) hasKeyword;
- (BOOL) hasStart;
- (BOOL) hasRows;
- (BOOL) hasMobileNum;
- (BOOL) hasImsi;
- (BOOL) hasMobileManufacturer;
- (BOOL) hasMobileType;
@property (readonly) int32_t type;
@property (readonly) int32_t cityId;
@property (readonly, retain) NSString* keyword;
@property (readonly) int32_t start;
@property (readonly) int32_t rows;
@property (readonly, retain) NSString* mobileNum;
@property (readonly, retain) NSString* imsi;
@property (readonly, retain) NSString* mobileManufacturer;
@property (readonly, retain) NSString* mobileType;
- (NSArray*) categoryIdsList;
- (int32_t) categoryIdsAtIndex:(int32_t) index;
- (NSArray*) companyIdsList;
- (NSString*) companyIdsAtIndex:(int32_t) index;

+ (QueryPublicInfoRequest*) defaultInstance;
- (QueryPublicInfoRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QueryPublicInfoRequest_Builder*) builder;
+ (QueryPublicInfoRequest_Builder*) builder;
+ (QueryPublicInfoRequest_Builder*) builderWithPrototype:(QueryPublicInfoRequest*) prototype;

+ (QueryPublicInfoRequest*) parseFromData:(NSData*) data;
+ (QueryPublicInfoRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QueryPublicInfoRequest*) parseFromInputStream:(NSInputStream*) input;
+ (QueryPublicInfoRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QueryPublicInfoRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QueryPublicInfoRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QueryPublicInfoRequest_Builder : PBGeneratedMessage_Builder {
@private
  QueryPublicInfoRequest* result;
}

- (QueryPublicInfoRequest*) defaultInstance;

- (QueryPublicInfoRequest_Builder*) clear;
- (QueryPublicInfoRequest_Builder*) clone;

- (QueryPublicInfoRequest*) build;
- (QueryPublicInfoRequest*) buildPartial;

- (QueryPublicInfoRequest_Builder*) mergeFrom:(QueryPublicInfoRequest*) other;
- (QueryPublicInfoRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QueryPublicInfoRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (int32_t) type;
- (QueryPublicInfoRequest_Builder*) setType:(int32_t) value;
- (QueryPublicInfoRequest_Builder*) clearType;

- (BOOL) hasCityId;
- (int32_t) cityId;
- (QueryPublicInfoRequest_Builder*) setCityId:(int32_t) value;
- (QueryPublicInfoRequest_Builder*) clearCityId;

- (NSArray*) categoryIdsList;
- (int32_t) categoryIdsAtIndex:(int32_t) index;
- (QueryPublicInfoRequest_Builder*) replaceCategoryIdsAtIndex:(int32_t) index with:(int32_t) value;
- (QueryPublicInfoRequest_Builder*) addCategoryIds:(int32_t) value;
- (QueryPublicInfoRequest_Builder*) addAllCategoryIds:(NSArray*) values;
- (QueryPublicInfoRequest_Builder*) clearCategoryIdsList;

- (BOOL) hasKeyword;
- (NSString*) keyword;
- (QueryPublicInfoRequest_Builder*) setKeyword:(NSString*) value;
- (QueryPublicInfoRequest_Builder*) clearKeyword;

- (BOOL) hasStart;
- (int32_t) start;
- (QueryPublicInfoRequest_Builder*) setStart:(int32_t) value;
- (QueryPublicInfoRequest_Builder*) clearStart;

- (BOOL) hasRows;
- (int32_t) rows;
- (QueryPublicInfoRequest_Builder*) setRows:(int32_t) value;
- (QueryPublicInfoRequest_Builder*) clearRows;

- (NSArray*) companyIdsList;
- (NSString*) companyIdsAtIndex:(int32_t) index;
- (QueryPublicInfoRequest_Builder*) replaceCompanyIdsAtIndex:(int32_t) index with:(NSString*) value;
- (QueryPublicInfoRequest_Builder*) addCompanyIds:(NSString*) value;
- (QueryPublicInfoRequest_Builder*) addAllCompanyIds:(NSArray*) values;
- (QueryPublicInfoRequest_Builder*) clearCompanyIdsList;

- (BOOL) hasMobileNum;
- (NSString*) mobileNum;
- (QueryPublicInfoRequest_Builder*) setMobileNum:(NSString*) value;
- (QueryPublicInfoRequest_Builder*) clearMobileNum;

- (BOOL) hasImsi;
- (NSString*) imsi;
- (QueryPublicInfoRequest_Builder*) setImsi:(NSString*) value;
- (QueryPublicInfoRequest_Builder*) clearImsi;

- (BOOL) hasMobileManufacturer;
- (NSString*) mobileManufacturer;
- (QueryPublicInfoRequest_Builder*) setMobileManufacturer:(NSString*) value;
- (QueryPublicInfoRequest_Builder*) clearMobileManufacturer;

- (BOOL) hasMobileType;
- (NSString*) mobileType;
- (QueryPublicInfoRequest_Builder*) setMobileType:(NSString*) value;
- (QueryPublicInfoRequest_Builder*) clearMobileType;
@end

@interface QueryPublicInfoResponse : PBGeneratedMessage {
@private
  BOOL hasNumfound_:1;
  BOOL hasStatus_:1;
  int64_t numfound;
  int32_t status;
  NSMutableArray* mutableCitiesList;
  NSMutableArray* mutableCategoriesList;
  NSMutableArray* mutableCompaniesList;
}
- (BOOL) hasStatus;
- (BOOL) hasNumfound;
@property (readonly) int32_t status;
@property (readonly) int64_t numfound;
- (NSArray*) citiesList;
- (QCity*) citiesAtIndex:(int32_t) index;
- (NSArray*) categoriesList;
- (QCategory*) categoriesAtIndex:(int32_t) index;
- (NSArray*) companiesList;
- (QCompany*) companiesAtIndex:(int32_t) index;

+ (QueryPublicInfoResponse*) defaultInstance;
- (QueryPublicInfoResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QueryPublicInfoResponse_Builder*) builder;
+ (QueryPublicInfoResponse_Builder*) builder;
+ (QueryPublicInfoResponse_Builder*) builderWithPrototype:(QueryPublicInfoResponse*) prototype;

+ (QueryPublicInfoResponse*) parseFromData:(NSData*) data;
+ (QueryPublicInfoResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QueryPublicInfoResponse*) parseFromInputStream:(NSInputStream*) input;
+ (QueryPublicInfoResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QueryPublicInfoResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QueryPublicInfoResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QueryPublicInfoResponse_Builder : PBGeneratedMessage_Builder {
@private
  QueryPublicInfoResponse* result;
}

- (QueryPublicInfoResponse*) defaultInstance;

- (QueryPublicInfoResponse_Builder*) clear;
- (QueryPublicInfoResponse_Builder*) clone;

- (QueryPublicInfoResponse*) build;
- (QueryPublicInfoResponse*) buildPartial;

- (QueryPublicInfoResponse_Builder*) mergeFrom:(QueryPublicInfoResponse*) other;
- (QueryPublicInfoResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QueryPublicInfoResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (int32_t) status;
- (QueryPublicInfoResponse_Builder*) setStatus:(int32_t) value;
- (QueryPublicInfoResponse_Builder*) clearStatus;

- (BOOL) hasNumfound;
- (int64_t) numfound;
- (QueryPublicInfoResponse_Builder*) setNumfound:(int64_t) value;
- (QueryPublicInfoResponse_Builder*) clearNumfound;

- (NSArray*) citiesList;
- (QCity*) citiesAtIndex:(int32_t) index;
- (QueryPublicInfoResponse_Builder*) replaceCitiesAtIndex:(int32_t) index with:(QCity*) value;
- (QueryPublicInfoResponse_Builder*) addCities:(QCity*) value;
- (QueryPublicInfoResponse_Builder*) addAllCities:(NSArray*) values;
- (QueryPublicInfoResponse_Builder*) clearCitiesList;

- (NSArray*) categoriesList;
- (QCategory*) categoriesAtIndex:(int32_t) index;
- (QueryPublicInfoResponse_Builder*) replaceCategoriesAtIndex:(int32_t) index with:(QCategory*) value;
- (QueryPublicInfoResponse_Builder*) addCategories:(QCategory*) value;
- (QueryPublicInfoResponse_Builder*) addAllCategories:(NSArray*) values;
- (QueryPublicInfoResponse_Builder*) clearCategoriesList;

- (NSArray*) companiesList;
- (QCompany*) companiesAtIndex:(int32_t) index;
- (QueryPublicInfoResponse_Builder*) replaceCompaniesAtIndex:(int32_t) index with:(QCompany*) value;
- (QueryPublicInfoResponse_Builder*) addCompanies:(QCompany*) value;
- (QueryPublicInfoResponse_Builder*) addAllCompanies:(NSArray*) values;
- (QueryPublicInfoResponse_Builder*) clearCompaniesList;
@end

