// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class CommentInfoRequest;
@class CommentInfoRequest_Builder;
@class CommentInfoResponse;
@class CommentInfoResponse_Builder;
@class QComment;
@class QComment_Builder;

@interface QueryCommentsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface QComment : PBGeneratedMessage {
@private
  BOOL hasMark1_:1;
  BOOL hasMark2_:1;
  BOOL hasMark3_:1;
  BOOL hasMark4_:1;
  BOOL hasMark5_:1;
  BOOL hasUserName_:1;
  BOOL hasPortraitUrl_:1;
  BOOL hasContent_:1;
  BOOL hasCommentTime_:1;
  int32_t mark1;
  int32_t mark2;
  int32_t mark3;
  int32_t mark4;
  int32_t mark5;
  NSString* userName;
  NSString* portraitUrl;
  NSString* content;
  NSString* commentTime;
}
- (BOOL) hasUserName;
- (BOOL) hasPortraitUrl;
- (BOOL) hasContent;
- (BOOL) hasMark1;
- (BOOL) hasMark2;
- (BOOL) hasMark3;
- (BOOL) hasMark4;
- (BOOL) hasMark5;
- (BOOL) hasCommentTime;
@property (readonly, retain) NSString* userName;
@property (readonly, retain) NSString* portraitUrl;
@property (readonly, retain) NSString* content;
@property (readonly) int32_t mark1;
@property (readonly) int32_t mark2;
@property (readonly) int32_t mark3;
@property (readonly) int32_t mark4;
@property (readonly) int32_t mark5;
@property (readonly, retain) NSString* commentTime;

+ (QComment*) defaultInstance;
- (QComment*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (QComment_Builder*) builder;
+ (QComment_Builder*) builder;
+ (QComment_Builder*) builderWithPrototype:(QComment*) prototype;

+ (QComment*) parseFromData:(NSData*) data;
+ (QComment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QComment*) parseFromInputStream:(NSInputStream*) input;
+ (QComment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (QComment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (QComment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface QComment_Builder : PBGeneratedMessage_Builder {
@private
  QComment* result;
}

- (QComment*) defaultInstance;

- (QComment_Builder*) clear;
- (QComment_Builder*) clone;

- (QComment*) build;
- (QComment*) buildPartial;

- (QComment_Builder*) mergeFrom:(QComment*) other;
- (QComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (QComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUserName;
- (NSString*) userName;
- (QComment_Builder*) setUserName:(NSString*) value;
- (QComment_Builder*) clearUserName;

- (BOOL) hasPortraitUrl;
- (NSString*) portraitUrl;
- (QComment_Builder*) setPortraitUrl:(NSString*) value;
- (QComment_Builder*) clearPortraitUrl;

- (BOOL) hasContent;
- (NSString*) content;
- (QComment_Builder*) setContent:(NSString*) value;
- (QComment_Builder*) clearContent;

- (BOOL) hasMark1;
- (int32_t) mark1;
- (QComment_Builder*) setMark1:(int32_t) value;
- (QComment_Builder*) clearMark1;

- (BOOL) hasMark2;
- (int32_t) mark2;
- (QComment_Builder*) setMark2:(int32_t) value;
- (QComment_Builder*) clearMark2;

- (BOOL) hasMark3;
- (int32_t) mark3;
- (QComment_Builder*) setMark3:(int32_t) value;
- (QComment_Builder*) clearMark3;

- (BOOL) hasMark4;
- (int32_t) mark4;
- (QComment_Builder*) setMark4:(int32_t) value;
- (QComment_Builder*) clearMark4;

- (BOOL) hasMark5;
- (int32_t) mark5;
- (QComment_Builder*) setMark5:(int32_t) value;
- (QComment_Builder*) clearMark5;

- (BOOL) hasCommentTime;
- (NSString*) commentTime;
- (QComment_Builder*) setCommentTime:(NSString*) value;
- (QComment_Builder*) clearCommentTime;
@end

@interface CommentInfoRequest : PBGeneratedMessage {
@private
  BOOL hasMark1_:1;
  BOOL hasMark2_:1;
  BOOL hasMark3_:1;
  BOOL hasMark4_:1;
  BOOL hasMark5_:1;
  BOOL hasStart_:1;
  BOOL hasRows_:1;
  BOOL hasCompanyId_:1;
  BOOL hasConent_:1;
  BOOL hasIPaddress_:1;
  int32_t mark1;
  int32_t mark2;
  int32_t mark3;
  int32_t mark4;
  int32_t mark5;
  int32_t start;
  int32_t rows;
  NSString* companyId;
  NSString* conent;
  NSString* iPaddress;
}
- (BOOL) hasCompanyId;
- (BOOL) hasConent;
- (BOOL) hasMark1;
- (BOOL) hasMark2;
- (BOOL) hasMark3;
- (BOOL) hasMark4;
- (BOOL) hasMark5;
- (BOOL) hasIPaddress;
- (BOOL) hasStart;
- (BOOL) hasRows;
@property (readonly, retain) NSString* companyId;
@property (readonly, retain) NSString* conent;
@property (readonly) int32_t mark1;
@property (readonly) int32_t mark2;
@property (readonly) int32_t mark3;
@property (readonly) int32_t mark4;
@property (readonly) int32_t mark5;
@property (readonly, retain) NSString* iPaddress;
@property (readonly) int32_t start;
@property (readonly) int32_t rows;

+ (CommentInfoRequest*) defaultInstance;
- (CommentInfoRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CommentInfoRequest_Builder*) builder;
+ (CommentInfoRequest_Builder*) builder;
+ (CommentInfoRequest_Builder*) builderWithPrototype:(CommentInfoRequest*) prototype;

+ (CommentInfoRequest*) parseFromData:(NSData*) data;
+ (CommentInfoRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommentInfoRequest*) parseFromInputStream:(NSInputStream*) input;
+ (CommentInfoRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommentInfoRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CommentInfoRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CommentInfoRequest_Builder : PBGeneratedMessage_Builder {
@private
  CommentInfoRequest* result;
}

- (CommentInfoRequest*) defaultInstance;

- (CommentInfoRequest_Builder*) clear;
- (CommentInfoRequest_Builder*) clone;

- (CommentInfoRequest*) build;
- (CommentInfoRequest*) buildPartial;

- (CommentInfoRequest_Builder*) mergeFrom:(CommentInfoRequest*) other;
- (CommentInfoRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CommentInfoRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCompanyId;
- (NSString*) companyId;
- (CommentInfoRequest_Builder*) setCompanyId:(NSString*) value;
- (CommentInfoRequest_Builder*) clearCompanyId;

- (BOOL) hasConent;
- (NSString*) conent;
- (CommentInfoRequest_Builder*) setConent:(NSString*) value;
- (CommentInfoRequest_Builder*) clearConent;

- (BOOL) hasMark1;
- (int32_t) mark1;
- (CommentInfoRequest_Builder*) setMark1:(int32_t) value;
- (CommentInfoRequest_Builder*) clearMark1;

- (BOOL) hasMark2;
- (int32_t) mark2;
- (CommentInfoRequest_Builder*) setMark2:(int32_t) value;
- (CommentInfoRequest_Builder*) clearMark2;

- (BOOL) hasMark3;
- (int32_t) mark3;
- (CommentInfoRequest_Builder*) setMark3:(int32_t) value;
- (CommentInfoRequest_Builder*) clearMark3;

- (BOOL) hasMark4;
- (int32_t) mark4;
- (CommentInfoRequest_Builder*) setMark4:(int32_t) value;
- (CommentInfoRequest_Builder*) clearMark4;

- (BOOL) hasMark5;
- (int32_t) mark5;
- (CommentInfoRequest_Builder*) setMark5:(int32_t) value;
- (CommentInfoRequest_Builder*) clearMark5;

- (BOOL) hasIPaddress;
- (NSString*) iPaddress;
- (CommentInfoRequest_Builder*) setIPaddress:(NSString*) value;
- (CommentInfoRequest_Builder*) clearIPaddress;

- (BOOL) hasStart;
- (int32_t) start;
- (CommentInfoRequest_Builder*) setStart:(int32_t) value;
- (CommentInfoRequest_Builder*) clearStart;

- (BOOL) hasRows;
- (int32_t) rows;
- (CommentInfoRequest_Builder*) setRows:(int32_t) value;
- (CommentInfoRequest_Builder*) clearRows;
@end

@interface CommentInfoResponse : PBGeneratedMessage {
@private
  BOOL hasNumFound_:1;
  BOOL hasStatus_:1;
  int64_t numFound;
  int32_t status;
  NSMutableArray* mutableCommentsList;
}
- (BOOL) hasNumFound;
- (BOOL) hasStatus;
@property (readonly) int64_t numFound;
@property (readonly) int32_t status;
- (NSArray*) commentsList;
- (QComment*) commentsAtIndex:(int32_t) index;

+ (CommentInfoResponse*) defaultInstance;
- (CommentInfoResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CommentInfoResponse_Builder*) builder;
+ (CommentInfoResponse_Builder*) builder;
+ (CommentInfoResponse_Builder*) builderWithPrototype:(CommentInfoResponse*) prototype;

+ (CommentInfoResponse*) parseFromData:(NSData*) data;
+ (CommentInfoResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommentInfoResponse*) parseFromInputStream:(NSInputStream*) input;
+ (CommentInfoResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CommentInfoResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CommentInfoResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CommentInfoResponse_Builder : PBGeneratedMessage_Builder {
@private
  CommentInfoResponse* result;
}

- (CommentInfoResponse*) defaultInstance;

- (CommentInfoResponse_Builder*) clear;
- (CommentInfoResponse_Builder*) clone;

- (CommentInfoResponse*) build;
- (CommentInfoResponse*) buildPartial;

- (CommentInfoResponse_Builder*) mergeFrom:(CommentInfoResponse*) other;
- (CommentInfoResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CommentInfoResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) commentsList;
- (QComment*) commentsAtIndex:(int32_t) index;
- (CommentInfoResponse_Builder*) replaceCommentsAtIndex:(int32_t) index with:(QComment*) value;
- (CommentInfoResponse_Builder*) addComments:(QComment*) value;
- (CommentInfoResponse_Builder*) addAllComments:(NSArray*) values;
- (CommentInfoResponse_Builder*) clearCommentsList;

- (BOOL) hasNumFound;
- (int64_t) numFound;
- (CommentInfoResponse_Builder*) setNumFound:(int64_t) value;
- (CommentInfoResponse_Builder*) clearNumFound;

- (BOOL) hasStatus;
- (int32_t) status;
- (CommentInfoResponse_Builder*) setStatus:(int32_t) value;
- (CommentInfoResponse_Builder*) clearStatus;
@end

