// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "BaseTypeProto.pb.h"

@class Address;
@class Address_Builder;
@class CallLog;
@class CallLog_Builder;
@class Category;
@class Category_Builder;
@class Email;
@class Email_Builder;
@class Employed;
@class Employed_Builder;
@class FileInfo;
@class FileInfo_Builder;
@class InstantMessage;
@class InstantMessage_Builder;
@class Name;
@class Name_Builder;
@class Phone;
@class Phone_Builder;
@class PortraitCardSummary;
@class PortraitCardSummary_Builder;
@class PortraitData;
@class PortraitData_Builder;
@class PortraitSummary;
@class PortraitSummary_Builder;
@class Sms;
@class SmsSummary;
@class SmsSummary_Builder;
@class Sms_Builder;
@class UabError;
@class UabError_Builder;
@class UploadMyPortraitData;
@class UploadMyPortraitData_Builder;
@class UploadPortraitData;
@class UploadPortraitData_Builder;
@class UploadPortraitRequest;
@class UploadPortraitRequest_Builder;
@class UploadPortraitResponse;
@class UploadPortraitResponse_Builder;
@class Website;
@class Website_Builder;

@interface UploadPortraitProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface UploadPortraitData : PBGeneratedMessage {
@private
  BOOL hasPortraitDataIndex_:1;
  BOOL hasPortraitData_:1;
  int32_t portraitDataIndex;
  PortraitData* portraitData;
}
- (BOOL) hasPortraitData;
- (BOOL) hasPortraitDataIndex;
@property (readonly, retain) PortraitData* portraitData;
@property (readonly) int32_t portraitDataIndex;

+ (UploadPortraitData*) defaultInstance;
- (UploadPortraitData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UploadPortraitData_Builder*) builder;
+ (UploadPortraitData_Builder*) builder;
+ (UploadPortraitData_Builder*) builderWithPrototype:(UploadPortraitData*) prototype;

+ (UploadPortraitData*) parseFromData:(NSData*) data;
+ (UploadPortraitData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadPortraitData*) parseFromInputStream:(NSInputStream*) input;
+ (UploadPortraitData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadPortraitData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UploadPortraitData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UploadPortraitData_Builder : PBGeneratedMessage_Builder {
@private
  UploadPortraitData* result;
}

- (UploadPortraitData*) defaultInstance;

- (UploadPortraitData_Builder*) clear;
- (UploadPortraitData_Builder*) clone;

- (UploadPortraitData*) build;
- (UploadPortraitData*) buildPartial;

- (UploadPortraitData_Builder*) mergeFrom:(UploadPortraitData*) other;
- (UploadPortraitData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UploadPortraitData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPortraitData;
- (PortraitData*) portraitData;
- (UploadPortraitData_Builder*) setPortraitData:(PortraitData*) value;
- (UploadPortraitData_Builder*) setPortraitDataBuilder:(PortraitData_Builder*) builderForValue;
- (UploadPortraitData_Builder*) mergePortraitData:(PortraitData*) value;
- (UploadPortraitData_Builder*) clearPortraitData;

- (BOOL) hasPortraitDataIndex;
- (int32_t) portraitDataIndex;
- (UploadPortraitData_Builder*) setPortraitDataIndex:(int32_t) value;
- (UploadPortraitData_Builder*) clearPortraitDataIndex;
@end

@interface UploadMyPortraitData : PBGeneratedMessage {
@private
  BOOL hasTimestamp_:1;
  BOOL hasPortraitSid_:1;
  BOOL hasPortraitData_:1;
  int64_t timestamp;
  int32_t portraitSid;
  PortraitData* portraitData;
}
- (BOOL) hasPortraitData;
- (BOOL) hasPortraitSid;
- (BOOL) hasTimestamp;
@property (readonly, retain) PortraitData* portraitData;
@property (readonly) int32_t portraitSid;
@property (readonly) int64_t timestamp;

+ (UploadMyPortraitData*) defaultInstance;
- (UploadMyPortraitData*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UploadMyPortraitData_Builder*) builder;
+ (UploadMyPortraitData_Builder*) builder;
+ (UploadMyPortraitData_Builder*) builderWithPrototype:(UploadMyPortraitData*) prototype;

+ (UploadMyPortraitData*) parseFromData:(NSData*) data;
+ (UploadMyPortraitData*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadMyPortraitData*) parseFromInputStream:(NSInputStream*) input;
+ (UploadMyPortraitData*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadMyPortraitData*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UploadMyPortraitData*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UploadMyPortraitData_Builder : PBGeneratedMessage_Builder {
@private
  UploadMyPortraitData* result;
}

- (UploadMyPortraitData*) defaultInstance;

- (UploadMyPortraitData_Builder*) clear;
- (UploadMyPortraitData_Builder*) clone;

- (UploadMyPortraitData*) build;
- (UploadMyPortraitData*) buildPartial;

- (UploadMyPortraitData_Builder*) mergeFrom:(UploadMyPortraitData*) other;
- (UploadMyPortraitData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UploadMyPortraitData_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPortraitData;
- (PortraitData*) portraitData;
- (UploadMyPortraitData_Builder*) setPortraitData:(PortraitData*) value;
- (UploadMyPortraitData_Builder*) setPortraitDataBuilder:(PortraitData_Builder*) builderForValue;
- (UploadMyPortraitData_Builder*) mergePortraitData:(PortraitData*) value;
- (UploadMyPortraitData_Builder*) clearPortraitData;

- (BOOL) hasPortraitSid;
- (int32_t) portraitSid;
- (UploadMyPortraitData_Builder*) setPortraitSid:(int32_t) value;
- (UploadMyPortraitData_Builder*) clearPortraitSid;

- (BOOL) hasTimestamp;
- (int64_t) timestamp;
- (UploadMyPortraitData_Builder*) setTimestamp:(int64_t) value;
- (UploadMyPortraitData_Builder*) clearTimestamp;
@end

@interface PortraitCardSummary : PBGeneratedMessage {
@private
  BOOL hasPortraitSid_:1;
  BOOL hasPortraitVersion_:1;
  int32_t portraitSid;
  int32_t portraitVersion;
}
- (BOOL) hasPortraitSid;
- (BOOL) hasPortraitVersion;
@property (readonly) int32_t portraitSid;
@property (readonly) int32_t portraitVersion;

+ (PortraitCardSummary*) defaultInstance;
- (PortraitCardSummary*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PortraitCardSummary_Builder*) builder;
+ (PortraitCardSummary_Builder*) builder;
+ (PortraitCardSummary_Builder*) builderWithPrototype:(PortraitCardSummary*) prototype;

+ (PortraitCardSummary*) parseFromData:(NSData*) data;
+ (PortraitCardSummary*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PortraitCardSummary*) parseFromInputStream:(NSInputStream*) input;
+ (PortraitCardSummary*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PortraitCardSummary*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PortraitCardSummary*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PortraitCardSummary_Builder : PBGeneratedMessage_Builder {
@private
  PortraitCardSummary* result;
}

- (PortraitCardSummary*) defaultInstance;

- (PortraitCardSummary_Builder*) clear;
- (PortraitCardSummary_Builder*) clone;

- (PortraitCardSummary*) build;
- (PortraitCardSummary*) buildPartial;

- (PortraitCardSummary_Builder*) mergeFrom:(PortraitCardSummary*) other;
- (PortraitCardSummary_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PortraitCardSummary_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPortraitSid;
- (int32_t) portraitSid;
- (PortraitCardSummary_Builder*) setPortraitSid:(int32_t) value;
- (PortraitCardSummary_Builder*) clearPortraitSid;

- (BOOL) hasPortraitVersion;
- (int32_t) portraitVersion;
- (PortraitCardSummary_Builder*) setPortraitVersion:(int32_t) value;
- (PortraitCardSummary_Builder*) clearPortraitVersion;
@end

@interface UploadPortraitRequest : PBGeneratedMessage {
@private
  BOOL hasBusinessCardPortrait_:1;
  PortraitData* businessCardPortrait;
  NSMutableArray* mutablePortraitList;
  NSMutableArray* mutableBusinessCardPortraitsList;
}
- (BOOL) hasBusinessCardPortrait;
@property (readonly, retain) PortraitData* businessCardPortrait;
- (NSArray*) portraitList;
- (UploadPortraitData*) portraitAtIndex:(int32_t) index;
- (NSArray*) businessCardPortraitsList;
- (UploadMyPortraitData*) businessCardPortraitsAtIndex:(int32_t) index;

+ (UploadPortraitRequest*) defaultInstance;
- (UploadPortraitRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UploadPortraitRequest_Builder*) builder;
+ (UploadPortraitRequest_Builder*) builder;
+ (UploadPortraitRequest_Builder*) builderWithPrototype:(UploadPortraitRequest*) prototype;

+ (UploadPortraitRequest*) parseFromData:(NSData*) data;
+ (UploadPortraitRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadPortraitRequest*) parseFromInputStream:(NSInputStream*) input;
+ (UploadPortraitRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadPortraitRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UploadPortraitRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UploadPortraitRequest_Builder : PBGeneratedMessage_Builder {
@private
  UploadPortraitRequest* result;
}

- (UploadPortraitRequest*) defaultInstance;

- (UploadPortraitRequest_Builder*) clear;
- (UploadPortraitRequest_Builder*) clone;

- (UploadPortraitRequest*) build;
- (UploadPortraitRequest*) buildPartial;

- (UploadPortraitRequest_Builder*) mergeFrom:(UploadPortraitRequest*) other;
- (UploadPortraitRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UploadPortraitRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) portraitList;
- (UploadPortraitData*) portraitAtIndex:(int32_t) index;
- (UploadPortraitRequest_Builder*) replacePortraitAtIndex:(int32_t) index with:(UploadPortraitData*) value;
- (UploadPortraitRequest_Builder*) addPortrait:(UploadPortraitData*) value;
- (UploadPortraitRequest_Builder*) addAllPortrait:(NSArray*) values;
- (UploadPortraitRequest_Builder*) clearPortraitList;

- (BOOL) hasBusinessCardPortrait;
- (PortraitData*) businessCardPortrait;
- (UploadPortraitRequest_Builder*) setBusinessCardPortrait:(PortraitData*) value;
- (UploadPortraitRequest_Builder*) setBusinessCardPortraitBuilder:(PortraitData_Builder*) builderForValue;
- (UploadPortraitRequest_Builder*) mergeBusinessCardPortrait:(PortraitData*) value;
- (UploadPortraitRequest_Builder*) clearBusinessCardPortrait;

- (NSArray*) businessCardPortraitsList;
- (UploadMyPortraitData*) businessCardPortraitsAtIndex:(int32_t) index;
- (UploadPortraitRequest_Builder*) replaceBusinessCardPortraitsAtIndex:(int32_t) index with:(UploadMyPortraitData*) value;
- (UploadPortraitRequest_Builder*) addBusinessCardPortraits:(UploadMyPortraitData*) value;
- (UploadPortraitRequest_Builder*) addAllBusinessCardPortraits:(NSArray*) values;
- (UploadPortraitRequest_Builder*) clearBusinessCardPortraitsList;
@end

@interface PortraitSummary : PBGeneratedMessage {
@private
  BOOL hasSid_:1;
  BOOL hasPortraitVersion_:1;
  int32_t sid;
  int32_t portraitVersion;
}
- (BOOL) hasSid;
- (BOOL) hasPortraitVersion;
@property (readonly) int32_t sid;
@property (readonly) int32_t portraitVersion;

+ (PortraitSummary*) defaultInstance;
- (PortraitSummary*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PortraitSummary_Builder*) builder;
+ (PortraitSummary_Builder*) builder;
+ (PortraitSummary_Builder*) builderWithPrototype:(PortraitSummary*) prototype;

+ (PortraitSummary*) parseFromData:(NSData*) data;
+ (PortraitSummary*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PortraitSummary*) parseFromInputStream:(NSInputStream*) input;
+ (PortraitSummary*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PortraitSummary*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PortraitSummary*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PortraitSummary_Builder : PBGeneratedMessage_Builder {
@private
  PortraitSummary* result;
}

- (PortraitSummary*) defaultInstance;

- (PortraitSummary_Builder*) clear;
- (PortraitSummary_Builder*) clone;

- (PortraitSummary*) build;
- (PortraitSummary*) buildPartial;

- (PortraitSummary_Builder*) mergeFrom:(PortraitSummary*) other;
- (PortraitSummary_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PortraitSummary_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSid;
- (int32_t) sid;
- (PortraitSummary_Builder*) setSid:(int32_t) value;
- (PortraitSummary_Builder*) clearSid;

- (BOOL) hasPortraitVersion;
- (int32_t) portraitVersion;
- (PortraitSummary_Builder*) setPortraitVersion:(int32_t) value;
- (PortraitSummary_Builder*) clearPortraitVersion;
@end

@interface UploadPortraitResponse : PBGeneratedMessage {
@private
  BOOL hasBusinessCardPortraitVersion_:1;
  int32_t businessCardPortraitVersion;
  NSMutableArray* mutablePortraitSummaryList;
  NSMutableArray* mutableBusinessCardPortraitVersionSummaryList;
}
- (BOOL) hasBusinessCardPortraitVersion;
@property (readonly) int32_t businessCardPortraitVersion;
- (NSArray*) portraitSummaryList;
- (PortraitSummary*) portraitSummaryAtIndex:(int32_t) index;
- (NSArray*) businessCardPortraitVersionSummaryList;
- (PortraitCardSummary*) businessCardPortraitVersionSummaryAtIndex:(int32_t) index;

+ (UploadPortraitResponse*) defaultInstance;
- (UploadPortraitResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UploadPortraitResponse_Builder*) builder;
+ (UploadPortraitResponse_Builder*) builder;
+ (UploadPortraitResponse_Builder*) builderWithPrototype:(UploadPortraitResponse*) prototype;

+ (UploadPortraitResponse*) parseFromData:(NSData*) data;
+ (UploadPortraitResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadPortraitResponse*) parseFromInputStream:(NSInputStream*) input;
+ (UploadPortraitResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadPortraitResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UploadPortraitResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UploadPortraitResponse_Builder : PBGeneratedMessage_Builder {
@private
  UploadPortraitResponse* result;
}

- (UploadPortraitResponse*) defaultInstance;

- (UploadPortraitResponse_Builder*) clear;
- (UploadPortraitResponse_Builder*) clone;

- (UploadPortraitResponse*) build;
- (UploadPortraitResponse*) buildPartial;

- (UploadPortraitResponse_Builder*) mergeFrom:(UploadPortraitResponse*) other;
- (UploadPortraitResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UploadPortraitResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) portraitSummaryList;
- (PortraitSummary*) portraitSummaryAtIndex:(int32_t) index;
- (UploadPortraitResponse_Builder*) replacePortraitSummaryAtIndex:(int32_t) index with:(PortraitSummary*) value;
- (UploadPortraitResponse_Builder*) addPortraitSummary:(PortraitSummary*) value;
- (UploadPortraitResponse_Builder*) addAllPortraitSummary:(NSArray*) values;
- (UploadPortraitResponse_Builder*) clearPortraitSummaryList;

- (BOOL) hasBusinessCardPortraitVersion;
- (int32_t) businessCardPortraitVersion;
- (UploadPortraitResponse_Builder*) setBusinessCardPortraitVersion:(int32_t) value;
- (UploadPortraitResponse_Builder*) clearBusinessCardPortraitVersion;

- (NSArray*) businessCardPortraitVersionSummaryList;
- (PortraitCardSummary*) businessCardPortraitVersionSummaryAtIndex:(int32_t) index;
- (UploadPortraitResponse_Builder*) replaceBusinessCardPortraitVersionSummaryAtIndex:(int32_t) index with:(PortraitCardSummary*) value;
- (UploadPortraitResponse_Builder*) addBusinessCardPortraitVersionSummary:(PortraitCardSummary*) value;
- (UploadPortraitResponse_Builder*) addAllBusinessCardPortraitVersionSummary:(NSArray*) values;
- (UploadPortraitResponse_Builder*) clearBusinessCardPortraitVersionSummaryList;
@end

