// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

#import "BaseTypeProto.pb.h"

@class Address;
@class Address_Builder;
@class Category;
@class Category_Builder;
@class Email;
@class Email_Builder;
@class Employed;
@class Employed_Builder;
@class InstantMessage;
@class InstantMessage_Builder;
@class Name;
@class Name_Builder;
@class Phone;
@class Phone_Builder;
@class PortraitData;
@class PortraitData_Builder;
@class Sms;
@class SmsSummary;
@class SmsSummary_Builder;
@class Sms_Builder;
@class UabError;
@class UabError_Builder;
@class UploadSmsRequest;
@class UploadSmsRequest_Builder;
@class Website;
@class Website_Builder;

@interface UploadSmsProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface UploadSmsRequest : PBGeneratedMessage {
@private
  NSMutableArray* mutableSmsList;
}
- (NSArray*) smsList;
- (Sms*) smsAtIndex:(int32_t) index;

+ (UploadSmsRequest*) defaultInstance;
- (UploadSmsRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UploadSmsRequest_Builder*) builder;
+ (UploadSmsRequest_Builder*) builder;
+ (UploadSmsRequest_Builder*) builderWithPrototype:(UploadSmsRequest*) prototype;

+ (UploadSmsRequest*) parseFromData:(NSData*) data;
+ (UploadSmsRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadSmsRequest*) parseFromInputStream:(NSInputStream*) input;
+ (UploadSmsRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadSmsRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UploadSmsRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UploadSmsRequest_Builder : PBGeneratedMessage_Builder {
@private
  UploadSmsRequest* result;
}

- (UploadSmsRequest*) defaultInstance;

- (UploadSmsRequest_Builder*) clear;
- (UploadSmsRequest_Builder*) clone;

- (UploadSmsRequest*) build;
- (UploadSmsRequest*) buildPartial;

- (UploadSmsRequest_Builder*) mergeFrom:(UploadSmsRequest*) other;
- (UploadSmsRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UploadSmsRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) smsList;
- (Sms*) smsAtIndex:(int32_t) index;
- (UploadSmsRequest_Builder*) replaceSmsAtIndex:(int32_t) index with:(Sms*) value;
- (UploadSmsRequest_Builder*) addSms:(Sms*) value;
- (UploadSmsRequest_Builder*) addAllSms:(NSArray*) values;
- (UploadSmsRequest_Builder*) clearSmsList;
@end

