// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AuthRequest;
@class AuthRequest_Builder;
@class AuthResponse;
@class AuthResponse_Builder;
typedef enum {
  AuthMethodImsi = 1,
  AuthMethodCtpassport = 2,
  AuthMethodMdn = 3,
} AuthMethod;

BOOL AuthMethodIsValidValue(AuthMethod value);


@interface AuthProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface AuthRequest : PBGeneratedMessage {
@private
  BOOL hasAccount_:1;
  BOOL hasPassword_:1;
  BOOL hasVerifySign_:1;
  BOOL hasMethod_:1;
  NSString* account;
  NSString* password;
  NSString* verifySign;
  AuthMethod method;
}
- (BOOL) hasMethod;
- (BOOL) hasAccount;
- (BOOL) hasPassword;
- (BOOL) hasVerifySign;
@property (readonly) AuthMethod method;
@property (readonly, retain) NSString* account;
@property (readonly, retain) NSString* password;
@property (readonly, retain) NSString* verifySign;

+ (AuthRequest*) defaultInstance;
- (AuthRequest*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthRequest_Builder*) builder;
+ (AuthRequest_Builder*) builder;
+ (AuthRequest_Builder*) builderWithPrototype:(AuthRequest*) prototype;

+ (AuthRequest*) parseFromData:(NSData*) data;
+ (AuthRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthRequest*) parseFromInputStream:(NSInputStream*) input;
+ (AuthRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthRequest_Builder : PBGeneratedMessage_Builder {
@private
  AuthRequest* result;
}

- (AuthRequest*) defaultInstance;

- (AuthRequest_Builder*) clear;
- (AuthRequest_Builder*) clone;

- (AuthRequest*) build;
- (AuthRequest*) buildPartial;

- (AuthRequest_Builder*) mergeFrom:(AuthRequest*) other;
- (AuthRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMethod;
- (AuthMethod) method;
- (AuthRequest_Builder*) setMethod:(AuthMethod) value;
- (AuthRequest_Builder*) clearMethod;

- (BOOL) hasAccount;
- (NSString*) account;
- (AuthRequest_Builder*) setAccount:(NSString*) value;
- (AuthRequest_Builder*) clearAccount;

- (BOOL) hasPassword;
- (NSString*) password;
- (AuthRequest_Builder*) setPassword:(NSString*) value;
- (AuthRequest_Builder*) clearPassword;

- (BOOL) hasVerifySign;
- (NSString*) verifySign;
- (AuthRequest_Builder*) setVerifySign:(NSString*) value;
- (AuthRequest_Builder*) clearVerifySign;
@end

@interface AuthResponse : PBGeneratedMessage {
@private
  BOOL hasSyncUserId_:1;
  BOOL hasToken_:1;
  BOOL hasPUserId_:1;
  BOOL hasMobileNum_:1;
  BOOL hasTokenExpires_:1;
  int64_t syncUserId;
  NSString* token;
  NSString* pUserId;
  NSString* mobileNum;
  int32_t tokenExpires;
}
- (BOOL) hasToken;
- (BOOL) hasTokenExpires;
- (BOOL) hasPUserId;
- (BOOL) hasSyncUserId;
- (BOOL) hasMobileNum;
@property (readonly, retain) NSString* token;
@property (readonly) int32_t tokenExpires;
@property (readonly, retain) NSString* pUserId;
@property (readonly) int64_t syncUserId;
@property (readonly, retain) NSString* mobileNum;

+ (AuthResponse*) defaultInstance;
- (AuthResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AuthResponse_Builder*) builder;
+ (AuthResponse_Builder*) builder;
+ (AuthResponse_Builder*) builderWithPrototype:(AuthResponse*) prototype;

+ (AuthResponse*) parseFromData:(NSData*) data;
+ (AuthResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthResponse*) parseFromInputStream:(NSInputStream*) input;
+ (AuthResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AuthResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AuthResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AuthResponse_Builder : PBGeneratedMessage_Builder {
@private
  AuthResponse* result;
}

- (AuthResponse*) defaultInstance;

- (AuthResponse_Builder*) clear;
- (AuthResponse_Builder*) clone;

- (AuthResponse*) build;
- (AuthResponse*) buildPartial;

- (AuthResponse_Builder*) mergeFrom:(AuthResponse*) other;
- (AuthResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AuthResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasToken;
- (NSString*) token;
- (AuthResponse_Builder*) setToken:(NSString*) value;
- (AuthResponse_Builder*) clearToken;

- (BOOL) hasTokenExpires;
- (int32_t) tokenExpires;
- (AuthResponse_Builder*) setTokenExpires:(int32_t) value;
- (AuthResponse_Builder*) clearTokenExpires;

- (BOOL) hasPUserId;
- (NSString*) pUserId;
- (AuthResponse_Builder*) setPUserId:(NSString*) value;
- (AuthResponse_Builder*) clearPUserId;

- (BOOL) hasSyncUserId;
- (int64_t) syncUserId;
- (AuthResponse_Builder*) setSyncUserId:(int64_t) value;
- (AuthResponse_Builder*) clearSyncUserId;

- (BOOL) hasMobileNum;
- (NSString*) mobileNum;
- (AuthResponse_Builder*) setMobileNum:(NSString*) value;
- (AuthResponse_Builder*) clearMobileNum;
@end

