// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "DownloadSmsProto.pb.h"

@implementation DownloadSmsProtoRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [DownloadSmsProtoRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    [BaseTypeProtoRoot registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface DownloadSmsRequest ()
@property (retain) NSMutableArray* mutableIdList;
@end

@implementation DownloadSmsRequest

@synthesize mutableIdList;
- (void) dealloc {
  self.mutableIdList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static DownloadSmsRequest* defaultDownloadSmsRequestInstance = nil;
+ (void) initialize {
  if (self == [DownloadSmsRequest class]) {
    defaultDownloadSmsRequestInstance = [[DownloadSmsRequest alloc] init];
  }
}
+ (DownloadSmsRequest*) defaultInstance {
  return defaultDownloadSmsRequestInstance;
}
- (DownloadSmsRequest*) defaultInstance {
  return defaultDownloadSmsRequestInstance;
}
- (NSArray*) idList {
  return mutableIdList;
}
- (NSString*) idAtIndex:(int32_t) index {
  id value = [mutableIdList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (NSString* element in self.mutableIdList) {
    [output writeString:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  {
    int32_t dataSize = 0;
    for (NSString* element in self.mutableIdList) {
      dataSize += computeStringSizeNoTag(element);
    }
    size += dataSize;
    size += 1 * self.mutableIdList.count;
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (DownloadSmsRequest*) parseFromData:(NSData*) data {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromData:data] build];
}
+ (DownloadSmsRequest*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsRequest*) parseFromInputStream:(NSInputStream*) input {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromInputStream:input] build];
}
+ (DownloadSmsRequest*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromCodedInputStream:input] build];
}
+ (DownloadSmsRequest*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsRequest*)[[[DownloadSmsRequest builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsRequest_Builder*) builder {
  return [[[DownloadSmsRequest_Builder alloc] init] autorelease];
}
+ (DownloadSmsRequest_Builder*) builderWithPrototype:(DownloadSmsRequest*) prototype {
  return [[DownloadSmsRequest builder] mergeFrom:prototype];
}
- (DownloadSmsRequest_Builder*) builder {
  return [DownloadSmsRequest builder];
}
@end

@interface DownloadSmsRequest_Builder()
@property (retain) DownloadSmsRequest* result;
@end

@implementation DownloadSmsRequest_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[DownloadSmsRequest alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (DownloadSmsRequest_Builder*) clear {
  self.result = [[[DownloadSmsRequest alloc] init] autorelease];
  return self;
}
- (DownloadSmsRequest_Builder*) clone {
  return [DownloadSmsRequest builderWithPrototype:result];
}
- (DownloadSmsRequest*) defaultInstance {
  return [DownloadSmsRequest defaultInstance];
}
- (DownloadSmsRequest*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (DownloadSmsRequest*) buildPartial {
  DownloadSmsRequest* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (DownloadSmsRequest_Builder*) mergeFrom:(DownloadSmsRequest*) other {
  if (other == [DownloadSmsRequest defaultInstance]) {
    return self;
  }
  if (other.mutableIdList.count > 0) {
    if (result.mutableIdList == nil) {
      result.mutableIdList = [NSMutableArray array];
    }
    [result.mutableIdList addObjectsFromArray:other.mutableIdList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (DownloadSmsRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (DownloadSmsRequest_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self addId:[input readString]];
        break;
      }
    }
  }
}
- (NSArray*) idList {
  if (result.mutableIdList == nil) {
    return [NSArray array];
  }
  return result.mutableIdList;
}
- (NSString*) idAtIndex:(int32_t) index {
  return [result idAtIndex:index];
}
- (DownloadSmsRequest_Builder*) replaceIdAtIndex:(int32_t) index with:(NSString*) value {
  [result.mutableIdList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (DownloadSmsRequest_Builder*) addId:(NSString*) value {
  if (result.mutableIdList == nil) {
    result.mutableIdList = [NSMutableArray array];
  }
  [result.mutableIdList addObject:value];
  return self;
}
- (DownloadSmsRequest_Builder*) addAllId:(NSArray*) values {
  if (result.mutableIdList == nil) {
    result.mutableIdList = [NSMutableArray array];
  }
  [result.mutableIdList addObjectsFromArray:values];
  return self;
}
- (DownloadSmsRequest_Builder*) clearIdList {
  result.mutableIdList = nil;
  return self;
}
@end

@interface DownloadSmsResponse ()
@property (retain) NSMutableArray* mutableSmsList;
@end

@implementation DownloadSmsResponse

@synthesize mutableSmsList;
- (void) dealloc {
  self.mutableSmsList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static DownloadSmsResponse* defaultDownloadSmsResponseInstance = nil;
+ (void) initialize {
  if (self == [DownloadSmsResponse class]) {
    defaultDownloadSmsResponseInstance = [[DownloadSmsResponse alloc] init];
  }
}
+ (DownloadSmsResponse*) defaultInstance {
  return defaultDownloadSmsResponseInstance;
}
- (DownloadSmsResponse*) defaultInstance {
  return defaultDownloadSmsResponseInstance;
}
- (NSArray*) smsList {
  return mutableSmsList;
}
- (Sms*) smsAtIndex:(int32_t) index {
  id value = [mutableSmsList objectAtIndex:index];
  return value;
}
- (BOOL) isInitialized {
  for (Sms* element in self.smsList) {
    if (!element.isInitialized) {
      return NO;
    }
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (Sms* element in self.smsList) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (Sms* element in self.smsList) {
    size += computeMessageSize(1, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (DownloadSmsResponse*) parseFromData:(NSData*) data {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromData:data] build];
}
+ (DownloadSmsResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsResponse*) parseFromInputStream:(NSInputStream*) input {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromInputStream:input] build];
}
+ (DownloadSmsResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromCodedInputStream:input] build];
}
+ (DownloadSmsResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DownloadSmsResponse*)[[[DownloadSmsResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DownloadSmsResponse_Builder*) builder {
  return [[[DownloadSmsResponse_Builder alloc] init] autorelease];
}
+ (DownloadSmsResponse_Builder*) builderWithPrototype:(DownloadSmsResponse*) prototype {
  return [[DownloadSmsResponse builder] mergeFrom:prototype];
}
- (DownloadSmsResponse_Builder*) builder {
  return [DownloadSmsResponse builder];
}
@end

@interface DownloadSmsResponse_Builder()
@property (retain) DownloadSmsResponse* result;
@end

@implementation DownloadSmsResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[DownloadSmsResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (DownloadSmsResponse_Builder*) clear {
  self.result = [[[DownloadSmsResponse alloc] init] autorelease];
  return self;
}
- (DownloadSmsResponse_Builder*) clone {
  return [DownloadSmsResponse builderWithPrototype:result];
}
- (DownloadSmsResponse*) defaultInstance {
  return [DownloadSmsResponse defaultInstance];
}
- (DownloadSmsResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (DownloadSmsResponse*) buildPartial {
  DownloadSmsResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (DownloadSmsResponse_Builder*) mergeFrom:(DownloadSmsResponse*) other {
  if (other == [DownloadSmsResponse defaultInstance]) {
    return self;
  }
  if (other.mutableSmsList.count > 0) {
    if (result.mutableSmsList == nil) {
      result.mutableSmsList = [NSMutableArray array];
    }
    [result.mutableSmsList addObjectsFromArray:other.mutableSmsList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (DownloadSmsResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (DownloadSmsResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        Sms_Builder* subBuilder = [Sms builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addSms:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) smsList {
  if (result.mutableSmsList == nil) { return [NSArray array]; }
  return result.mutableSmsList;
}
- (Sms*) smsAtIndex:(int32_t) index {
  return [result smsAtIndex:index];
}
- (DownloadSmsResponse_Builder*) replaceSmsAtIndex:(int32_t) index with:(Sms*) value {
  [result.mutableSmsList replaceObjectAtIndex:index withObject:value];
  return self;
}
- (DownloadSmsResponse_Builder*) addAllSms:(NSArray*) values {
  if (result.mutableSmsList == nil) {
    result.mutableSmsList = [NSMutableArray array];
  }
  [result.mutableSmsList addObjectsFromArray:values];
  return self;
}
- (DownloadSmsResponse_Builder*) clearSmsList {
  result.mutableSmsList = nil;
  return self;
}
- (DownloadSmsResponse_Builder*) addSms:(Sms*) value {
  if (result.mutableSmsList == nil) {
    result.mutableSmsList = [NSMutableArray array];
  }
  [result.mutableSmsList addObject:value];
  return self;
}
@end

