// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class GetContactListVersionResponse;
@class GetContactListVersionResponse_Builder;

@interface GetContactListVersionProtoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GetContactListVersionResponse : PBGeneratedMessage {
@private
  BOOL hasContactListVersion_:1;
  int32_t contactListVersion;
}
- (BOOL) hasContactListVersion;
@property (readonly) int32_t contactListVersion;

+ (GetContactListVersionResponse*) defaultInstance;
- (GetContactListVersionResponse*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetContactListVersionResponse_Builder*) builder;
+ (GetContactListVersionResponse_Builder*) builder;
+ (GetContactListVersionResponse_Builder*) builderWithPrototype:(GetContactListVersionResponse*) prototype;

+ (GetContactListVersionResponse*) parseFromData:(NSData*) data;
+ (GetContactListVersionResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetContactListVersionResponse*) parseFromInputStream:(NSInputStream*) input;
+ (GetContactListVersionResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetContactListVersionResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetContactListVersionResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetContactListVersionResponse_Builder : PBGeneratedMessage_Builder {
@private
  GetContactListVersionResponse* result;
}

- (GetContactListVersionResponse*) defaultInstance;

- (GetContactListVersionResponse_Builder*) clear;
- (GetContactListVersionResponse_Builder*) clone;

- (GetContactListVersionResponse*) build;
- (GetContactListVersionResponse*) buildPartial;

- (GetContactListVersionResponse_Builder*) mergeFrom:(GetContactListVersionResponse*) other;
- (GetContactListVersionResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetContactListVersionResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasContactListVersion;
- (int32_t) contactListVersion;
- (GetContactListVersionResponse_Builder*) setContactListVersion:(int32_t) value;
- (GetContactListVersionResponse_Builder*) clearContactListVersion;
@end

