// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "GetUserCloudSummaryProto.pb.h"

@implementation GetUserCloudSummaryProtoRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [GetUserCloudSummaryProtoRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface GetUserCloudSummaryResponse ()
@property int32_t contactCount;
@property int32_t messageCount;
@property int32_t callLogCount;
@end

@implementation GetUserCloudSummaryResponse

- (BOOL) hasContactCount {
  return !!hasContactCount_;
}
- (void) setHasContactCount:(BOOL) value {
  hasContactCount_ = !!value;
}
@synthesize contactCount;
- (BOOL) hasMessageCount {
  return !!hasMessageCount_;
}
- (void) setHasMessageCount:(BOOL) value {
  hasMessageCount_ = !!value;
}
@synthesize messageCount;
- (BOOL) hasCallLogCount {
  return !!hasCallLogCount_;
}
- (void) setHasCallLogCount:(BOOL) value {
  hasCallLogCount_ = !!value;
}
@synthesize callLogCount;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.contactCount = 0;
    self.messageCount = 0;
    self.callLogCount = 0;
  }
  return self;
}
static GetUserCloudSummaryResponse* defaultGetUserCloudSummaryResponseInstance = nil;
+ (void) initialize {
  if (self == [GetUserCloudSummaryResponse class]) {
    defaultGetUserCloudSummaryResponseInstance = [[GetUserCloudSummaryResponse alloc] init];
  }
}
+ (GetUserCloudSummaryResponse*) defaultInstance {
  return defaultGetUserCloudSummaryResponseInstance;
}
- (GetUserCloudSummaryResponse*) defaultInstance {
  return defaultGetUserCloudSummaryResponseInstance;
}
- (BOOL) isInitialized {
  if (!self.hasContactCount) {
    return NO;
  }
  if (!self.hasMessageCount) {
    return NO;
  }
  if (!self.hasCallLogCount) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasContactCount) {
    [output writeInt32:1 value:self.contactCount];
  }
  if (self.hasMessageCount) {
    [output writeInt32:2 value:self.messageCount];
  }
  if (self.hasCallLogCount) {
    [output writeInt32:3 value:self.callLogCount];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasContactCount) {
    size += computeInt32Size(1, self.contactCount);
  }
  if (self.hasMessageCount) {
    size += computeInt32Size(2, self.messageCount);
  }
  if (self.hasCallLogCount) {
    size += computeInt32Size(3, self.callLogCount);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (GetUserCloudSummaryResponse*) parseFromData:(NSData*) data {
  return (GetUserCloudSummaryResponse*)[[[GetUserCloudSummaryResponse builder] mergeFromData:data] build];
}
+ (GetUserCloudSummaryResponse*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetUserCloudSummaryResponse*)[[[GetUserCloudSummaryResponse builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (GetUserCloudSummaryResponse*) parseFromInputStream:(NSInputStream*) input {
  return (GetUserCloudSummaryResponse*)[[[GetUserCloudSummaryResponse builder] mergeFromInputStream:input] build];
}
+ (GetUserCloudSummaryResponse*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetUserCloudSummaryResponse*)[[[GetUserCloudSummaryResponse builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetUserCloudSummaryResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (GetUserCloudSummaryResponse*)[[[GetUserCloudSummaryResponse builder] mergeFromCodedInputStream:input] build];
}
+ (GetUserCloudSummaryResponse*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetUserCloudSummaryResponse*)[[[GetUserCloudSummaryResponse builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetUserCloudSummaryResponse_Builder*) builder {
  return [[[GetUserCloudSummaryResponse_Builder alloc] init] autorelease];
}
+ (GetUserCloudSummaryResponse_Builder*) builderWithPrototype:(GetUserCloudSummaryResponse*) prototype {
  return [[GetUserCloudSummaryResponse builder] mergeFrom:prototype];
}
- (GetUserCloudSummaryResponse_Builder*) builder {
  return [GetUserCloudSummaryResponse builder];
}
@end

@interface GetUserCloudSummaryResponse_Builder()
@property (retain) GetUserCloudSummaryResponse* result;
@end

@implementation GetUserCloudSummaryResponse_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[GetUserCloudSummaryResponse alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (GetUserCloudSummaryResponse_Builder*) clear {
  self.result = [[[GetUserCloudSummaryResponse alloc] init] autorelease];
  return self;
}
- (GetUserCloudSummaryResponse_Builder*) clone {
  return [GetUserCloudSummaryResponse builderWithPrototype:result];
}
- (GetUserCloudSummaryResponse*) defaultInstance {
  return [GetUserCloudSummaryResponse defaultInstance];
}
- (GetUserCloudSummaryResponse*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (GetUserCloudSummaryResponse*) buildPartial {
  GetUserCloudSummaryResponse* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (GetUserCloudSummaryResponse_Builder*) mergeFrom:(GetUserCloudSummaryResponse*) other {
  if (other == [GetUserCloudSummaryResponse defaultInstance]) {
    return self;
  }
  if (other.hasContactCount) {
    [self setContactCount:other.contactCount];
  }
  if (other.hasMessageCount) {
    [self setMessageCount:other.messageCount];
  }
  if (other.hasCallLogCount) {
    [self setCallLogCount:other.callLogCount];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (GetUserCloudSummaryResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (GetUserCloudSummaryResponse_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setContactCount:[input readInt32]];
        break;
      }
      case 16: {
        [self setMessageCount:[input readInt32]];
        break;
      }
      case 24: {
        [self setCallLogCount:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasContactCount {
  return result.hasContactCount;
}
- (int32_t) contactCount {
  return result.contactCount;
}
- (GetUserCloudSummaryResponse_Builder*) setContactCount:(int32_t) value {
  result.hasContactCount = YES;
  result.contactCount = value;
  return self;
}
- (GetUserCloudSummaryResponse_Builder*) clearContactCount {
  result.hasContactCount = NO;
  result.contactCount = 0;
  return self;
}
- (BOOL) hasMessageCount {
  return result.hasMessageCount;
}
- (int32_t) messageCount {
  return result.messageCount;
}
- (GetUserCloudSummaryResponse_Builder*) setMessageCount:(int32_t) value {
  result.hasMessageCount = YES;
  result.messageCount = value;
  return self;
}
- (GetUserCloudSummaryResponse_Builder*) clearMessageCount {
  result.hasMessageCount = NO;
  result.messageCount = 0;
  return self;
}
- (BOOL) hasCallLogCount {
  return result.hasCallLogCount;
}
- (int32_t) callLogCount {
  return result.callLogCount;
}
- (GetUserCloudSummaryResponse_Builder*) setCallLogCount:(int32_t) value {
  result.hasCallLogCount = YES;
  result.callLogCount = value;
  return self;
}
- (GetUserCloudSummaryResponse_Builder*) clearCallLogCount {
  result.hasCallLogCount = NO;
  result.callLogCount = 0;
  return self;
}
@end

