platform :ios, '8.0'
use_frameworks!
target 'testAPP' do
pod 'FLEX', '~> 2.4.0', :configurations => ['Debug']
pod 'YYKit', '~> 1.0.9'
pod 'AFNetworking', '~> 3.2.1'
pod 'Masonry', '~> 1.1.0'
pod 'MJRefresh', '~> 3.1.15.7'
pod 'MBProgressHUD', '~> 1.1.0'
end
